=== averbraeck/opentrafficsim/release/1.02.02/ots-xsd/src/main/resources/xsd/1.00.00/ots-definitions.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.opentrafficsim.org/ots"
  xmlns:ots="http://www.opentrafficsim.org/ots" xmlns="http://www.opentrafficsim.org/ots" xmlns:xi="http://www.w3.org/2001/XInclude"
  xmlns:fn="http://www.w3.org/2005/xpath-functions" elementFormDefault="qualified">

  <xsd:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2009/01/xml.xsd" />
  <xsd:import namespace="http://www.w3.org/2001/XInclude" schemaLocation="http://www.w3.org/2001/xinclude.xsd" />

  <xsd:include schemaLocation="ots-types.xsd" />

  <!-- ================================================================================================== -->
  <!-- =============================================== ELEMENTS ========================================= -->
  <!-- ================================================================================================== -->

  <xsd:element name="GLOBAL">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="SPEEDGTUCOLORER" minOccurs="0" maxOccurs="1">
          <xsd:complexType>
            <xsd:attribute name="MAXSPEED" type="SPEEDTYPE" use="required" />
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="ACCELERATIONGTUCOLORER" minOccurs="0" maxOccurs="1">
          <xsd:complexType>
            <xsd:attribute name="MAXDECELERATION" type="ACCELERATIONTYPE" use="required" />
            <xsd:attribute name="MAXACCELERATION" type="ACCELERATIONTYPE" use="required" />
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="LANECHANGEURGEGTUCOLORER" minOccurs="0" maxOccurs="1">
          <xsd:complexType>
            <xsd:attribute name="MINLANECHANGEDISTANCE" type="POSITIVELENGTHTYPE" use="required" />
            <xsd:attribute name="HORIZON" type="POSITIVELENGTHTYPE" use="required" />
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
      <xsd:attribute ref="xml:base" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="GTUTYPE">
    <xsd:complexType>
      <xsd:attribute name="ID" type="xsd:string" use="required" />
      <xsd:attribute ref="xml:base" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="GTU">
    <xsd:complexType>
      <xsd:attribute name="ID" type="xsd:string" use="required" />
      <xsd:attribute name="GTUTYPE" type="xsd:string" use="required" />
      <xsd:attribute name="LENGTH" type="LENGTHDISTTYPE" use="required" />
      <xsd:attribute name="WIDTH" type="LENGTHDISTTYPE" use="required" />
      <xsd:attribute name="MAXSPEED" type="SPEEDDISTTYPE" use="required" />
      <xsd:attribute ref="xml:base" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="GTUMIX">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="GTU" minOccurs="1" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:attribute name="ID" type="xsd:string" use="required" />
            <xsd:attribute name="WEIGHT" type="xsd:double" use="required" />
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
      <xsd:attribute name="ID" type="xsd:string" use="required" />
      <xsd:attribute ref="xml:base" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="ROADTYPE">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="SPEEDLIMIT" minOccurs="1" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:attribute name="GTUTYPE" type="xsd:string" use="required" />
            <xsd:attribute name="LEGALSPEEDLIMIT" type="SPEEDTYPE" use="required" />
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
      <xsd:attribute name="ID" type="xsd:string" use="required" />
      <xsd:attribute name="DEFAULTLANEWIDTH" type="POSITIVELENGTHTYPE" use="required" />
      <xsd:attribute name="DEFAULTLANEKEEPING" type="LANEKEEPINGTYPE" use="required" />
      <xsd:attribute name="DEFAULTOVERTAKING" type="OVERTAKINGTYPE" use="required" />
      <xsd:attribute ref="xml:base" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="LANETYPE">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="SPEEDLIMIT" minOccurs="1" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:attribute name="GTUTYPE" type="xsd:string" use="required" />
            <xsd:attribute name="LEGALSPEEDLIMIT" type="SPEEDTYPE" use="optional" />
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
      <xsd:attribute name="ID" type="xsd:string" use="required" />
      <xsd:attribute name="DEFAULTLANEWIDTH" type="POSITIVELENGTHTYPE" use="optional" />
      <xsd:attribute name="DEFAULTLANEKEEPING" type="LANEKEEPINGTYPE" use="optional" />
      <xsd:attribute ref="xml:base" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="ROADLAYOUT">
    <xsd:complexType>
      <xsd:sequence>

        <xsd:element name="SPEEDLIMIT" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:attribute name="GTUTYPE" type="xsd:string" use="required" />
            <xsd:attribute name="LEGALSPEEDLIMIT" type="SPEEDTYPE" use="optional" />
          </xsd:complexType>
        </xsd:element>

        <xsd:choice minOccurs="1" maxOccurs="unbounded">

          <xsd:element name="LANE" minOccurs="0" maxOccurs="unbounded">
            <xsd:complexType>
              <xsd:sequence minOccurs="0" maxOccurs="unbounded">
                <xsd:element name="SPEEDLIMIT" minOccurs="1" maxOccurs="unbounded">
                  <xsd:complexType>
                    <xsd:attribute name="GTUTYPE" type="xsd:string" use="required" />
                    <xsd:attribute name="LEGALSPEEDLIMIT" type="SPEEDTYPE" use="optional" />
                  </xsd:complexType>
                </xsd:element>
              </xsd:sequence>
              <xsd:attribute name="ID" type="xsd:string" use="required" />
              <xsd:attribute name="LANETYPE" type="xsd:string" use="optional" />
              <!-- either OFFSET, or OFFSETSTART and OFFSETEND... -->
              <xsd:attribute name="OFFSET" type="LENGTHTYPE" use="optional" />
              <xsd:attribute name="OFFSETSTART" type="LENGTHTYPE" use="optional" />
              <xsd:attribute name="OFFSETEND" type="LENGTHTYPE" use="optional" />
              <xsd:attribute name="WIDTH" type="POSITIVELENGTHTYPE" use="optional" />
              <xsd:attribute name="DIRECTION" type="DRIVINGDIRECTIONTYPE" use="required" />
              <xsd:attribute name="COLOR" type="COLORTYPE" use="optional" />
              <xsd:attribute name="OVERTAKING" type="OVERTAKINGTYPE" use="optional" />
            </xsd:complexType>
          </xsd:element>

          <xsd:element name="NOTRAFFICLANE" minOccurs="0" maxOccurs="unbounded">
            <xsd:complexType>
              <xsd:attribute name="ID" type="xsd:string" use="optional" />
              <!-- either OFFSET, or OFFSETSTART and OFFSETEND... -->
              <xsd:attribute name="OFFSET" type="LENGTHTYPE" use="optional" />
              <xsd:attribute name="OFFSETSTART" type="LENGTHTYPE" use="optional" />
              <xsd:attribute name="OFFSETEND" type="LENGTHTYPE" use="optional" />
              <xsd:attribute name="WIDTH" type="POSITIVELENGTHTYPE" use="optional" />
              <xsd:attribute name="COLOR" type="COLORTYPE" use="optional" />
            </xsd:complexType>
          </xsd:element>

          <xsd:element name="SHOULDER" minOccurs="0" maxOccurs="unbounded">
            <xsd:complexType>
              <xsd:attribute name="ID" type="xsd:string" use="optional" />
              <!-- either OFFSET, or OFFSETSTART and OFFSETEND... -->
              <xsd:attribute name="OFFSET" type="LENGTHTYPE" use="optional" />
              <xsd:attribute name="OFFSETSTART" type="LENGTHTYPE" use="optional" />
              <xsd:attribute name="OFFSETEND" type="LENGTHTYPE" use="optional" />
              <xsd:attribute name="WIDTH" type="POSITIVELENGTHTYPE" use="optional" />
              <xsd:attribute name="COLOR" type="COLORTYPE" use="optional" />
            </xsd:complexType>
          </xsd:element>

          <xsd:element name="STRIPE" minOccurs="0" maxOccurs="unbounded">
            <xsd:complexType>
              <xsd:attribute name="ID" type="xsd:string" use="optional" />
              <xsd:attribute name="TYPE" type="STRIPETYPE" use="required" />
              <xsd:attribute name="OFFSET" type="LENGTHTYPE" use="required" />
              <xsd:attribute name="WIDTH" type="POSITIVELENGTHTYPE" use="optional" />
              <xsd:attribute name="COLOR" type="COLORTYPE" use="optional" />
            </xsd:complexType>
          </xsd:element>

        </xsd:choice>
      </xsd:sequence>
      <xsd:attribute name="ID" type="xsd:string" use="required" />
      <xsd:attribute name="ROADTYPE" type="xsd:string" use="required" />
      <xsd:attribute name="WIDTH" type="POSITIVELENGTHTYPE" use="optional" />
      <xsd:attribute name="LANEKEEPING" type="LANEKEEPINGTYPE" use="optional" />
      <xsd:attribute name="OVERTAKING" type="OVERTAKINGTYPE" use="optional" />
      <xsd:attribute ref="xml:base" />
    </xsd:complexType>
  </xsd:element>

  <!-- ================================================================================================== -->
  <!-- ============================================== DEFINITIONS ======================================= -->
  <!-- ================================================================================================== -->

  <xsd:element name="DEFINITIONS">
    <xsd:complexType mixed="true">
      <xsd:sequence>
        <xsd:element ref="GLOBAL" minOccurs="0" maxOccurs="1" />
        <xsd:choice minOccurs="1" maxOccurs="unbounded">
          <xsd:element ref="xi:include" minOccurs="0" maxOccurs="unbounded" />
          <xsd:element ref="GTUTYPE" minOccurs="0" maxOccurs="unbounded" />
          <xsd:element ref="GTU" minOccurs="0" maxOccurs="unbounded" />
          <xsd:element ref="GTUMIX" minOccurs="0" maxOccurs="unbounded" />
          <xsd:element ref="ROADTYPE" minOccurs="0" maxOccurs="unbounded" />
          <xsd:element ref="LANETYPE" minOccurs="0" maxOccurs="unbounded" />
          <xsd:element ref="ROADLAYOUT" minOccurs="0" maxOccurs="unbounded" />
        </xsd:choice>
      </xsd:sequence>
      <xsd:attribute ref="xml:base" />
    </xsd:complexType>

  </xsd:element>

</xsd:schema>

=== averbraeck/opentrafficsim/release/0.03.03/ots-core/src/main/resources/roadtypes.xml
<?xml version="1.0" encoding="UTF-8"?>
<DEFINITIONS xmlns="http://www.opentrafficsim.org/ots" xmlns:ots="http://www.opentrafficsim.org/ots"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xi="http://www.w3.org/2001/XInclude"
  xsi:schemaLocation="http://www.opentrafficsim.org/ots http://www.opentrafficsim.org/docs/ots-definitions.xsd">

  <GLOBAL DEFAULTLANEWIDTH="3.6m" DEFAULTMAXSPEED="100km/h" />

  <LANETYPE NAME="HIGHWAY" />
  <LANETYPE NAME="NOTRUCK" />
  <LANETYPE NAME="BICYCLEPATH" />

  <ROADTYPE NAME="r1">
    <SHOULDER WIDTH="2m" OFFSET="-7.1m" COLOR="GREEN" />
    <STRIPE TYPE="SOLID" OFFSET="-6.1m" />
    <NOTRAFFICLANE OFFSET="-4.85m" WIDTH="2.5m" />
    <STRIPE TYPE="SOLID" OFFSET="-3.6m" />
    <LANE NAME="A1" TYPE="HIGHWAY" OFFSET="-1.8m" WIDTH="3.6m" DIRECTION="FORWARD" SPEED="100km/h" />
    <STRIPE TYPE="SOLID" OFFSET="0m" WIDTH="20cm" COLOR="#FFFFFF" />
    <NOTRAFFICLANE OFFSET="1.25m" WIDTH="2.5m" />
    <STRIPE TYPE="SOLID" OFFSET="2.5m" />
    <SHOULDER WIDTH="2m" OFFSET="3.5m" COLOR="GREEN" />
  </ROADTYPE>

  <ROADTYPE NAME="r2">
    <SHOULDER WIDTH="2m" OFFSET="-3.5m" COLOR="GREEN" />
    <STRIPE TYPE="SOLID" OFFSET="-2.5m" />
    <NOTRAFFICLANE WIDTH="2.5m" OFFSET="-1.25m" />
    <STRIPE TYPE="SOLID" OFFSET="0m" />
    <LANE NAME="A1" TYPE="HIGHWAY" OFFSET="1.8m" WIDTH="3.6m" DIRECTION="FORWARD" SPEED="100km/h" />
    <STRIPE TYPE="DASHED" OFFSET="3.6m" COLOR="RGB(255,255,255)" />
    <LANE NAME="A2" TYPE="HIGHWAY" OFFSET="5.4m" WIDTH="3.6m" DIRECTION="FORWARD" SPEED="100km/h" />
    <STRIPE TYPE="SOLID" OFFSET="7.2m" WIDTH="20cm" COLOR="#FFFFFF" />
    <NOTRAFFICLANE OFFSET="8.45m" WIDTH="2.5m" />
    <STRIPE TYPE="SOLID" OFFSET="9.7m" />
    <SHOULDER WIDTH="2m" OFFSET="10.7m" COLOR="GREEN" />
  </ROADTYPE>

  <ROADTYPE NAME="r3">
    <SHOULDER WIDTH="2m" OFFSET="-7.1m" COLOR="GREEN" />
    <STRIPE TYPE="SOLID" OFFSET="-6.1m" />
    <NOTRAFFICLANE OFFSET="-4.85m" WIDTH="2.5m" />
    <STRIPE TYPE="SOLID" OFFSET="-3.6m" />
    <LANE NAME="A1" TYPE="HIGHWAY" OFFSET="-1.8m" WIDTH="3.6m" DIRECTION="FORWARD" SPEED="100km/h" />
    <STRIPE TYPE="DASHED" OFFSET="0m" COLOR="RGB(255,255,255)" />
    <LANE NAME="A2" TYPE="HIGHWAY" OFFSET="1.8m" WIDTH="3.6m" DIRECTION="FORWARD" SPEED="100km/h" />
    <STRIPE TYPE="DASHED" OFFSET="3.6m" COLOR="RGB(255,255,255)" />
    <LANE NAME="A3" TYPE="HIGHWAY" OFFSET="5.4m" WIDTH="3.6m" DIRECTION="FORWARD" SPEED="100km/h" />
    <STRIPE TYPE="SOLID" OFFSET="7.2m" WIDTH="20cm" COLOR="#FFFFFF" />
    <NOTRAFFICLANE OFFSET="8.45m" WIDTH="2.5m" />
    <STRIPE TYPE="SOLID" OFFSET="9.7m" />
    <SHOULDER WIDTH="2m" OFFSET="10.7m" COLOR="GREEN" />
  </ROADTYPE>

</DEFINITIONS>

=== averbraeck/opentrafficsim/release/0.13.03/ots-parser-xml/src/test/resources/roadtypes.xml
<?xml version="1.0" encoding="UTF-8"?>
<DEFINITIONS xmlns="http://www.opentrafficsim.org/ots" xmlns:ots="http://www.opentrafficsim.org/ots"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xi="http://www.w3.org/2001/XInclude"
  xsi:schemaLocation="http://www.opentrafficsim.org/ots http://www.opentrafficsim.org/docs/current/ots-definitions.xsd">

  <GLOBAL />

  <GTUTYPE NAME="CAR" />
  <GTUTYPE NAME="TRUCK" />

  <ROADTYPE NAME="HIGHWAY" DEFAULTLANEWIDTH="3.6m" DEFAULTLANEKEEPING="KEEPRIGHT"
    DEFAULTOVERTAKING="LEFTSET([CAR, TRUCK] OVERTAKE [ALL]) RIGHTSPEED(40 km/h)">
    <SPEEDLIMIT GTUTYPE="CAR" LEGALSPEEDLIMIT="130 km/h"/>
    <SPEEDLIMIT GTUTYPE="TRUCK" LEGALSPEEDLIMIT="90 km/h"/>
  </ROADTYPE>

  <ROADLAYOUT NAME="r1" ROADTYPE="HIGHWAY">
    <SHOULDER WIDTH="2m" OFFSET="-7.1m" COLOR="GREEN" />
    <STRIPE TYPE="SOLID" OFFSET="-6.1m" />
    <NOTRAFFICLANE OFFSET="-4.85m" WIDTH="2.5m" />
    <STRIPE TYPE="SOLID" OFFSET="-3.6m" />
    <LANE NAME="A1" OFFSET="-1.8m" WIDTH="3.6m" DIRECTION="FORWARD" />
    <STRIPE TYPE="SOLID" OFFSET="0m" WIDTH="20cm" COLOR="#FFFFFF" />
    <NOTRAFFICLANE OFFSET="1.25m" WIDTH="2.5m" />
    <STRIPE TYPE="SOLID" OFFSET="2.5m" />
    <SHOULDER WIDTH="2m" OFFSET="3.5m" COLOR="GREEN" />
  </ROADLAYOUT>

  <ROADLAYOUT NAME="r2" ROADTYPE="HIGHWAY">
    <SHOULDER WIDTH="2m" OFFSET="-3.5m" COLOR="GREEN" />
    <STRIPE TYPE="SOLID" OFFSET="-2.5m" />
    <NOTRAFFICLANE WIDTH="2.5m" OFFSET="-1.25m" />
    <STRIPE TYPE="SOLID" OFFSET="0m" />
    <LANE NAME="A1" OFFSET="1.8m" WIDTH="3.6m" DIRECTION="FORWARD" />
    <STRIPE TYPE="DASHED" OFFSET="3.6m" COLOR="RGB(255,255,255)" />
    <LANE NAME="A2" OFFSET="5.4m" WIDTH="3.6m" DIRECTION="FORWARD" />
    <STRIPE TYPE="SOLID" OFFSET="7.2m" WIDTH="20cm" COLOR="#FFFFFF" />
    <NOTRAFFICLANE OFFSET="8.45m" WIDTH="2.5m" />
    <STRIPE TYPE="SOLID" OFFSET="9.7m" />
    <SHOULDER WIDTH="2m" OFFSET="10.7m" COLOR="GREEN" />
  </ROADLAYOUT>

  <ROADLAYOUT NAME="r3" ROADTYPE="HIGHWAY">
    <SHOULDER WIDTH="2m" OFFSET="-7.1m" COLOR="GREEN" />
    <STRIPE TYPE="SOLID" OFFSET="-6.1m" />
    <NOTRAFFICLANE OFFSET="-4.85m" WIDTH="2.5m" />
    <STRIPE TYPE="SOLID" OFFSET="-3.6m" />
    <LANE NAME="A1" OFFSET="-1.8m" WIDTH="3.6m" DIRECTION="FORWARD" />
    <STRIPE TYPE="DASHED" OFFSET="0m" COLOR="RGB(255,255,255)" />
    <LANE NAME="A2" OFFSET="1.8m" WIDTH="3.6m" DIRECTION="FORWARD" />
    <STRIPE TYPE="DASHED" OFFSET="3.6m" COLOR="RGB(255,255,255)" />
    <LANE NAME="A3" OFFSET="5.4m" WIDTH="3.6m" DIRECTION="FORWARD" />
    <STRIPE TYPE="SOLID" OFFSET="7.2m" WIDTH="20cm" COLOR="#FFFFFF" />
    <NOTRAFFICLANE OFFSET="8.45m" WIDTH="2.5m" />
    <STRIPE TYPE="SOLID" OFFSET="9.7m" />
    <SHOULDER WIDTH="2m" OFFSET="10.7m" COLOR="GREEN" />
  </ROADLAYOUT>

</DEFINITIONS>
