=== averbraeck/opentrafficsim/trunk/ots-core/src/main/resources/ots-network.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.opentrafficsim.org/ots"
  xmlns:ots="http://www.opentrafficsim.org/ots" xmlns="http://www.opentrafficsim.org/ots" xmlns:xi="http://www.w3.org/2001/XInclude"
  elementFormDefault="qualified">

  <xsd:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2009/01/xml.xsd" />
  <xsd:import namespace="http://www.w3.org/2001/XInclude" schemaLocation="http://www.w3.org/2001/xinclude.xsd" />

  <xsd:include schemaLocation="http://www.opentrafficsim.org/docs/ots-definitions.xsd" />

  <!-- ================================================================================================== -->
  <!-- ================================================ NETWORK ========================================= -->
  <!-- ================================================================================================== -->

  <xsd:element name="NODE">
    <xsd:complexType>
      <xsd:attribute name="NAME" type="xsd:ID" use="required"></xsd:attribute>
      <xsd:attribute name="COORDINATE" type="COORDINATETYPE" use="optional"></xsd:attribute>
      <xsd:attribute name="ANGLE" type="ANGLETYPE" use="optional"></xsd:attribute>
      <xsd:attribute ref="xml:base"></xsd:attribute>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="LINK">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:choice>
          <xsd:element name="STRAIGHT">
            <xsd:complexType>
              <xsd:attribute name="LENGTH" type="LENGTHTYPE" use="required"></xsd:attribute>
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="ARC">
            <xsd:complexType>
              <xsd:attribute name="RADIUS" type="LENGTHTYPE" use="required"></xsd:attribute>
              <xsd:attribute name="ANGLE" type="ANGLETYPE" use="required"></xsd:attribute>
              <xsd:attribute name="DIRECTION" type="LEFTRIGHTTYPE" use="required"></xsd:attribute>
            </xsd:complexType>
          </xsd:element>
        </xsd:choice>

        <xsd:element name="LANEOVERRIDE" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:attribute name="LANE" type="xsd:string" use="required"></xsd:attribute>
            <xsd:attribute name="SPEED" type="SPEEDTYPE" use="optional"></xsd:attribute>
            <xsd:attribute name="DIRECTION" type="DIRECTIONTYPE" use="optional"></xsd:attribute>
            <xsd:attribute name="COLOR" type="COLORTYPE" use="optional"></xsd:attribute>
          </xsd:complexType>
        </xsd:element>

        <xsd:element ref="ROADTYPE" minOccurs="0" maxOccurs="1" />

        <!-- TODO EITHER GTU or GTUMIX should be present... -->
        <!-- TODO Maximum one of ROUTE, ROUTEMIX, SHORTESTROUTE, SHORTESTROUTEMIX should be present... -->
        <xsd:element name="GENERATOR" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:attribute name="LANE" type="xsd:string" use="required"></xsd:attribute>
            <xsd:attribute name="POSITION" type="LENGTHBEGINENDTYPE" use="optional"></xsd:attribute>
            <xsd:attribute name="GTU" type="xsd:IDREF" use="optional"></xsd:attribute>
            <xsd:attribute name="GTUMIX" type="xsd:IDREF" use="optional"></xsd:attribute>
            <xsd:attribute name="IAT" type="TIMEDISTTYPE" use="required"></xsd:attribute>
            <xsd:attribute name="INITIALSPEED" type="SPEEDDISTTYPE" use="required"></xsd:attribute>
            <xsd:attribute name="MAXGTU" type="xsd:double" use="optional"></xsd:attribute>
            <xsd:attribute name="STARTTIME" type="TIMETYPE" use="optional"></xsd:attribute>
            <xsd:attribute name="ENDTIME" type="TIMETYPE" use="optional"></xsd:attribute>
            <xsd:attribute name="ROUTE" type="xsd:IDREF" use="required"></xsd:attribute>
            <xsd:attribute name="GTUCOLORER" type="GTUCOLORERTYPE" use="required"></xsd:attribute>
          </xsd:complexType>
        </xsd:element>

        <!-- TODO EITHER GTU or GTUMIX should be present... -->
        <!-- TODO Maximum one of ROUTE, ROUTEMIX, SHORTESTROUTE, SHORTESTROUTEMIX should be present... -->
        <xsd:element name="LISTGENERATOR" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:attribute name="URI" type="xsd:anyURI" use="required"></xsd:attribute>
            <xsd:attribute name="LANE" type="xsd:string" use="required"></xsd:attribute>
            <xsd:attribute name="POSITION" type="LENGTHBEGINENDTYPE" use="optional"></xsd:attribute>
            <xsd:attribute name="GTU" type="xsd:IDREF" use="optional"></xsd:attribute>
            <xsd:attribute name="GTUMIX" type="xsd:IDREF" use="optional"></xsd:attribute>
            <xsd:attribute name="INITIALSPEED" type="SPEEDDISTTYPE" use="required"></xsd:attribute>
            <xsd:attribute name="GTUCOLORER" type="GTUCOLORERTYPE" use="required"></xsd:attribute>
          </xsd:complexType>
        </xsd:element>

        <!-- TODO EITHER GTU or GTUGROUP should be present... -->
        <!-- TODO Maximum one of ROUTE, ROUTEMIX, SHORTESTROUTE, SHORTESTROUTEMIX should be present... -->
        <xsd:element name="FILL" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:attribute name="LANE" type="xsd:string" use="required"></xsd:attribute>
            <xsd:attribute name="GTU" type="xsd:IDREF" use="optional"></xsd:attribute>
            <xsd:attribute name="GTUMIX" type="xsd:IDREF" use="optional"></xsd:attribute>
            <xsd:attribute name="DISTANCE" type="LENGTHDISTTYPE" use="required"></xsd:attribute>
            <xsd:attribute name="INITIALSPEED" type="SPEEDDISTTYPE" use="required"></xsd:attribute>
            <xsd:attribute name="MAXGTU" type="xsd:double" use="optional"></xsd:attribute>
            <xsd:attribute name="ROUTE" type="xsd:IDREF" use="required"></xsd:attribute>
          </xsd:complexType>
        </xsd:element>

        <xsd:element name="BLOCK" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:attribute name="LANE" type="xsd:string" use="required"></xsd:attribute>
            <xsd:attribute name="POSITION" type="LENGTHBEGINENDTYPE" use="required"></xsd:attribute>
          </xsd:complexType>
        </xsd:element>

        <xsd:element name="BLOCKONOFF" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:attribute name="LANE" type="xsd:string" use="required"></xsd:attribute>
            <xsd:attribute name="POSITION" type="LENGTHBEGINENDTYPE" use="required"></xsd:attribute>
          </xsd:complexType>
        </xsd:element>

        <xsd:element name="SENSOR" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:attribute name="NAME" type="xsd:string" use="optional"></xsd:attribute>
            <xsd:attribute name="LANE" type="xsd:string" use="required"></xsd:attribute>
            <xsd:attribute name="POSITION" type="LENGTHBEGINENDTYPE" use="required"></xsd:attribute>
            <xsd:attribute name="CLASS" type="CLASSNAMETYPE" use="required"></xsd:attribute>
            <xsd:attribute name="TRIGGER" type="GTUPOSITIONTYPE" use="required"></xsd:attribute>
          </xsd:complexType>
        </xsd:element>

        <xsd:element name="SINK" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:attribute name="LANE" type="xsd:string" use="required"></xsd:attribute>
            <xsd:attribute name="POSITION" type="LENGTHBEGINENDTYPE" use="required"></xsd:attribute>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>

      <xsd:attribute name="NAME" type="xsd:ID" use="required"></xsd:attribute>
      <xsd:attribute name="NODESTART" type="xsd:IDREF" use="required"></xsd:attribute>
      <xsd:attribute name="NODEEND" type="xsd:IDREF" use="required"></xsd:attribute>
      <xsd:attribute name="ROADTYPE" type="xsd:IDREF" use="optional"></xsd:attribute>
      <xsd:attribute name="OFFSETSTART" type="SIGNEDLENGTHTYPE" use="optional"></xsd:attribute>
      <xsd:attribute name="OFFSETEND" type="SIGNEDLENGTHTYPE" use="optional"></xsd:attribute>
      <xsd:attribute name="ROTATIONSTART" type="ANGLETYPE" use="optional"></xsd:attribute>
      <xsd:attribute name="ROTATIONEND" type="ANGLETYPE" use="optional"></xsd:attribute>
      <xsd:attribute ref="xml:base"></xsd:attribute>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="ROUTE">
    <xsd:complexType>
      <xsd:attribute name="NAME" type="xsd:ID" use="required"></xsd:attribute>
      <xsd:attribute name="NODELIST" type="xsd:IDREFS" use="required"></xsd:attribute>
      <xsd:attribute ref="xml:base"></xsd:attribute>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="SHORTESTROUTE">
    <xsd:complexType>
      <xsd:attribute name="NAME" type="xsd:ID" use="required"></xsd:attribute>
      <xsd:attribute name="FROM" type="xsd:IDREF" use="required"></xsd:attribute>
      <xsd:attribute name="TO" type="xsd:IDREF" use="required"></xsd:attribute>
      <xsd:attribute name="VIA" type="xsd:IDREFS" use="optional"></xsd:attribute>
      <xsd:attribute name="DISTANCECOST" type="DISTANCECOSTTYPE" use="required"></xsd:attribute>
      <xsd:attribute name="TIMECOST" type="TIMECOSTTYPE" use="required"></xsd:attribute>
      <xsd:attribute ref="xml:base"></xsd:attribute>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="ROUTEMIX">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="ROUTE" minOccurs="1" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:attribute name="NAME" type="xsd:IDREF" use="required"></xsd:attribute>
            <xsd:attribute name="WEIGHT" type="xsd:double" use="required"></xsd:attribute>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
      <xsd:attribute name="NAME" type="xsd:string" use="required"></xsd:attribute>
      <xsd:attribute ref="xml:base"></xsd:attribute>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="SHORTESTROUTEMIX">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="SHORTESTROUTE" minOccurs="1" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:attribute name="NAME" type="xsd:IDREF" use="required"></xsd:attribute>
            <xsd:attribute name="WEIGHT" type="xsd:double" use="required"></xsd:attribute>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
      <xsd:attribute name="NAME" type="xsd:ID" use="required"></xsd:attribute>
      <xsd:attribute ref="xml:base"></xsd:attribute>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="NETWORK">
    <xsd:complexType mixed="true">
      <xsd:sequence>
        <xsd:choice minOccurs="1" maxOccurs="unbounded">
          <xsd:element ref="DEFINITIONS" minOccurs="0" maxOccurs="unbounded" />
          <xsd:element ref="xi:include" minOccurs="0" maxOccurs="unbounded" />
          <xsd:element ref="NODE" minOccurs="0" maxOccurs="unbounded" />
          <xsd:element ref="LINK" minOccurs="0" maxOccurs="unbounded" />
          <xsd:element ref="ROUTE" minOccurs="0" maxOccurs="unbounded" />
          <xsd:element ref="ROUTEMIX" minOccurs="0" maxOccurs="unbounded" />
          <xsd:element ref="SHORTESTROUTE" minOccurs="0" maxOccurs="unbounded" />
          <xsd:element ref="SHORTESTROUTEMIX" minOccurs="0" maxOccurs="unbounded" />
        </xsd:choice>
      </xsd:sequence>
      <xsd:attribute ref="xml:base"></xsd:attribute>
    </xsd:complexType>
  </xsd:element>

</xsd:schema>

=== averbraeck/opentrafficsim/trunk/ots-core/src/main/resources/offset-example.xml
<?xml version="1.0" encoding="UTF-8" ?>
<NETWORK xmlns="http://www.opentrafficsim.org/ots" xmlns:ots="http://www.opentrafficsim.org/ots" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.opentrafficsim.org/ots http://www.opentrafficsim.org/docs/ots-network.xsd" xmlns:xi="http://www.w3.org/2001/XInclude">

  <xi:include href="roadtypes.xml" parse="xml" />

  <DEFINITIONS>

    <GTU NAME="BICYCLE" GTUTYPE="BICYCLE" FOLLOWING="IDM" LENGTH="CONST(2) m" WIDTH="CONST(0.5) m" LANECHANGE="ALTRUISTIC"
      MAXSPEED="CONST(25) km/h" />
    <GTU NAME="CAR" GTUTYPE="CAR" FOLLOWING="IDM+" LENGTH="CONST(5) m" WIDTH="UNIF(1.7, 2) m" LANECHANGE="EGOISTIC"
      MAXSPEED="TRIA(50,80,120) km/h" />
    <GTU NAME="TRUCK" GTUTYPE="TRUCK" FOLLOWING="IDM+" LENGTH="UNIF(16,24) m" WIDTH="UNIF(2.2, 2.7) m" LANECHANGE="ALTRUISTIC"
      MAXSPEED="CONST(100) km/h" />

    <GTUMIX NAME="C60T40">
      <GTU NAME="CAR" WEIGHT="60"></GTU>
      <GTU NAME="TRUCK" WEIGHT="40"></GTU>
    </GTUMIX>

    <GTUMIX NAME="C80T20">
      <GTU NAME="CAR" WEIGHT="80" />
      <GTU NAME="TRUCK" WEIGHT="20" />
    </GTUMIX>

    <COMPATIBILITY LANETYPE="HIGHWAY" GTULIST="CAR TRUCK" />
    <COMPATIBILITY LANETYPE="NOTRUCK" GTULIST="CAR" />
    <COMPATIBILITY LANETYPE="BICYCLEPATH" GTULIST="BICYCLE" />

  </DEFINITIONS>


  <NODE NAME="N1" COORDINATE="(0.0, 0.0)" ANGLE="90 deg" />
  <NODE NAME="N1a" />
  <NODE NAME="N2" />
  <NODE NAME="NE" />
  <NODE NAME="NE2" />

  <ROUTE NAME="CIRCLE" NODELIST="NE N1 N1a N2 N1" />

  <LINK NAME="L1" NODESTART="N1" NODEEND="N1a" ROADTYPE="r3">
    <ARC RADIUS="1000m" ANGLE="45 deg" DIRECTION="L" />
    <BLOCK LANE="A1" POSITION="END-10cm" />
    <BLOCK LANE="A2" POSITION="END-10cm" />
  </LINK>

  <LINK NAME="L1a" NODESTART="N1a" NODEEND="N2" ROADTYPE="r2">
    <ARC RADIUS="1000m" ANGLE="135 deg" DIRECTION="L" />
  </LINK>

  <LINK NAME="L2" NODESTART="N2" NODEEND="N1" ROADTYPE="r2">
    <ARC RADIUS="1000m" ANGLE="180 deg" DIRECTION="L" />
    <SENSOR LANE="A1" POSITION="END-13m" CLASS="nl.grontmij.GuusSensor" TRIGGER="FRONT" />
  </LINK>

  <LINK NAME="ENTRY" NODESTART="NE" NODEEND="N1" ROADTYPE="r1">
    <STRAIGHT LENGTH="200m" />
  </LINK>

  <LINK NAME="ENTRY2" NODESTART="NE2" NODEEND="NE" ROADTYPE="r1">
    <STRAIGHT LENGTH="200m" />
    <LANEOVERRIDE LANE="A1" SPEED="50 km/h" />
    <!-- GENERATOR LANE="A1" IAT="EXPO(30) s" INITIALSPEED="CONST(0.0) km/h" MAXGTU="50" GTUMIX="C80T20" ROUTE="CIRCLE" GTUCOLORER="SWITCHABLE" 
      / -->
    <!-- GENERATOR LANE="A1" POSITION="10m" IAT="EXPO(30) s" INITIALSPEED="CONST(0.0) km/h" MAXGTU="250" GTU="CAR" ROUTE="CIRCLE" 
      GTUCOLORER="SWITCHABLE" / -->
    <GENERATOR LANE="A1" POSITION="10m" IAT="CONST(10) s" INITIALSPEED="CONST(0.0) km/h" MAXGTU="250" GTU="CAR"
      ROUTE="CIRCLE" GTUCOLORER="SWITCHABLE" />
  </LINK>

</NETWORK>

=== averbraeck/opentrafficsim/trunk/ots-demo/src/main/resources/conflict/TJunction.xml
<?xml version="1.0" encoding="UTF-8"?>

<NETWORK xmlns="http://www.opentrafficsim.org/ots" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.opentrafficsim.org/ots http://www.opentrafficsim.org/docs/current/ots-network.xsd">

  <DEFINITIONS>

    <GLOBAL />

    <GTUTYPE NAME="CAR" />

    <GTU NAME="CAR" GTUTYPE="CAR" LENGTH="UNIF(4,7) m" WIDTH="UNIF(1.7, 2) m" MAXSPEED="CONST(120) km/h" />

    <ROADTYPE NAME="URBAN" DEFAULTLANEWIDTH="3.5m" DEFAULTLANEKEEPING="KEEPRIGHT" DEFAULTOVERTAKING="NONE">
      <SPEEDLIMIT GTUTYPE="CAR" LEGALSPEEDLIMIT="50km/h" />
    </ROADTYPE>

    <ROADLAYOUT NAME="RIGHT" ROADTYPE="URBAN">
      <SHOULDER WIDTH="2m" OFFSET="-8.75m" COLOR="RGB(0,128,0)" />
      <!--STRIPE TYPE="SOLID" OFFSET="-7.75m" / -->
      <LANE NAME="LANE" OFFSET="-6.0m" WIDTH="3.5m" DIRECTION="FORWARD" />
      <!--STRIPE TYPE="SOLID" OFFSET="-4.25m" / -->
      <SHOULDER WIDTH="2m" OFFSET="-3.25m" COLOR="RGB(0,128,0)" />
    </ROADLAYOUT>

  </DEFINITIONS>

  <NODE NAME="E" COORDINATE="(300,0)" />
  <NODE NAME="S" COORDINATE="(0,-300)" />
  <NODE NAME="W" COORDINATE="(-300,0)" />
  <NODE NAME="EC" COORDINATE="(18.8,0)" />
  <NODE NAME="SC" COORDINATE="(0,-18.8)" />
  <NODE NAME="WC" COORDINATE="(-18.8,0)" />

  <ROUTE NODELIST="E EC WC W" NAME="EW" />
  <ROUTE NODELIST="E EC SC S" NAME="ES" />
  <ROUTE NODELIST="W WC EC E" NAME="WE" />
  <ROUTE NODELIST="W WC SC S" NAME="WS" />
  <ROUTE NODELIST="S SC WC W" NAME="SW" />
  <ROUTE NODELIST="S SC EC E" NAME="SE" />

  <ROUTEMIX NAME="E">
    <ROUTE WEIGHT="0.8" NAME="EW" />
    <ROUTE WEIGHT="0.2" NAME="ES" />
  </ROUTEMIX>

  <ROUTEMIX NAME="W">
    <ROUTE WEIGHT="0.8" NAME="WE" />
    <ROUTE WEIGHT="0.2" NAME="WS" />
  </ROUTEMIX>

  <ROUTEMIX NAME="S">
    <ROUTE WEIGHT="0.5" NAME="SW" />
    <ROUTE WEIGHT="0.5" NAME="SE" />
  </ROUTEMIX>

  <LINK NAME="EEC" NODESTART="E" NODEEND="EC" ROADLAYOUT="RIGHT">
    <STRAIGHT />
    <GENERATOR LANE="LANE" POSITION="10m" IAT="EXPO(10) s" INITIALSPEED="CONST(0.0) km/h" GTU="CAR" ROUTEMIX="E"
      GTUCOLORER="SWITCHABLE" TACTICALPLANNER="LMRS" />
  </LINK>

  <LINK NAME="ECE" NODESTART="EC" NODEEND="E" ROADLAYOUT="RIGHT">
    <STRAIGHT />
  </LINK>

  <LINK NAME="SSC" NODESTART="S" NODEEND="SC" ROADLAYOUT="RIGHT">
    <STRAIGHT />
    <GENERATOR LANE="LANE" POSITION="10m" IAT="EXPO(10) s" INITIALSPEED="CONST(0.0) km/h" GTU="CAR" ROUTEMIX="S"
      GTUCOLORER="SWITCHABLE" TACTICALPLANNER="LMRS" />
  </LINK>

  <LINK NAME="SCS" NODESTART="SC" NODEEND="S" ROADLAYOUT="RIGHT">
    <STRAIGHT />
  </LINK>

  <LINK NAME="WWC" NODESTART="W" NODEEND="WC" ROADLAYOUT="RIGHT">
    <STRAIGHT />
    <GENERATOR LANE="LANE" POSITION="10m" IAT="EXPO(8) s" INITIALSPEED="CONST(0.0) km/h" GTU="CAR" ROUTEMIX="W"
      GTUCOLORER="SWITCHABLE" TACTICALPLANNER="LMRS" />
  </LINK>

  <LINK NAME="WCW" NODESTART="WC" NODEEND="W" ROADLAYOUT="RIGHT">
    <STRAIGHT />
  </LINK>

  <LINK NAME="ECWC" NODESTART="EC" NODEEND="WC" ROADLAYOUT="RIGHT">
    <STRAIGHT />
  </LINK>

  <LINK NAME="ECSC" NODESTART="EC" NODEEND="SC" ROADLAYOUT="RIGHT">
    <ARC RADIUS="18.8m" ANGLE="90 deg" DIRECTION="L" />
  </LINK>

  <LINK NAME="SCEC" NODESTART="SC" NODEEND="EC" ROADLAYOUT="RIGHT">
    <ARC RADIUS="18.8m" ANGLE="90 deg" DIRECTION="R" />
  </LINK>

  <LINK NAME="SCWC" NODESTART="SC" NODEEND="WC" ROADLAYOUT="RIGHT">
    <ARC RADIUS="18.8m" ANGLE="90 deg" DIRECTION="L" />
  </LINK>

  <LINK NAME="WCEC" NODESTART="WC" NODEEND="EC" ROADLAYOUT="RIGHT">
    <STRAIGHT />
  </LINK>

  <LINK NAME="WCSC" NODESTART="WC" NODEEND="SC" ROADLAYOUT="RIGHT">
    <ARC RADIUS="18.8m" ANGLE="90 deg" DIRECTION="R" />
  </LINK>

</NETWORK>

=== averbraeck/opentrafficsim/trunk/ots-road/src/main/resources/Testnetwork2.x.xml
<?xml version="1.0" encoding="UTF-8" ?>
<NETWORK xmlns="http://www.opentrafficsim.org/ots" xmlns:ots="http://www.opentrafficsim.org/ots" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.opentrafficsim.org/ots http://www.opentrafficsim.org/docs/ots-network.xsd" xmlns:xi="http://www.w3.org/2001/XInclude">

  <DEFINITIONS>

    <GLOBAL DEFAULTLANEWIDTH="3m" DEFAULTMAXSPEED="100 km/h" DEFAULTOVERTAKING="NONE" DEFAULTLANEKEEPING="KEEPLANE"></GLOBAL>

    <GTUTYPE NAME="CAR" />

    <GTU NAME="CAR" GTUTYPE="CAR" FOLLOWING="IDM+" LENGTH="CONST(4.5) m" WIDTH="CONST(2) m" LANECHANGE="EGOISTIC"
      MAXSPEED="CONST(80) km/h" />

    <LANETYPE NAME="HIGHWAY" />

    <COMPATIBILITY LANETYPE="HIGHWAY">
      <GTU NAME="CAR" />
    </COMPATIBILITY>

    <ROADTYPE NAME="RT1ln_ref-4">
      <LANE NAME="A1" TYPE="HIGHWAY" OFFSET="-12m" WIDTH="3m" DIRECTION="FORWARD" SPEED="120km/h" />
    </ROADTYPE>

    <ROADTYPE NAME="RT1ln_ref-3">
      <LANE NAME="A1" TYPE="HIGHWAY" OFFSET="-9m" WIDTH="3m" DIRECTION="FORWARD" SPEED="120km/h" />
    </ROADTYPE>

    <ROADTYPE NAME="RT1ln_ref-2">
      <LANE NAME="A1" TYPE="HIGHWAY" OFFSET="-6m" WIDTH="3m" DIRECTION="FORWARD" SPEED="120km/h" />
    </ROADTYPE>

    <ROADTYPE NAME="RT1ln_ref0">
      <LANE NAME="A1" TYPE="HIGHWAY" OFFSET="0m" WIDTH="3m" DIRECTION="FORWARD" SPEED="120km/h" />
    </ROADTYPE>

    <ROADTYPE NAME="RT3ln_ref-2">
      <LANE NAME="A1" TYPE="HIGHWAY" OFFSET="-12m" WIDTH="3m" DIRECTION="FORWARD" SPEED="120km/h" />
      <STRIPE TYPE="DASHED" OFFSET="-10.5m" />
      <LANE NAME="A2" TYPE="HIGHWAY" OFFSET="-9m" WIDTH="3m" DIRECTION="FORWARD" SPEED="120km/h" />
      <STRIPE TYPE="DASHED" OFFSET="-7.5m" />
      <LANE NAME="A3" TYPE="HIGHWAY" OFFSET="-6m" WIDTH="3m" DIRECTION="FORWARD" SPEED="120km/h" />
    </ROADTYPE>

  </DEFINITIONS>

  <NODE NAME="N_A1" COORDINATE="(-300, 0)" ANGLE="0 deg" />
  <NODE NAME="N_A2" COORDINATE="(-200, 0)" />
  <NODE NAME="N_A3" COORDINATE="(-20, 0)" />

  <NODE NAME="N_B1" COORDINATE="(0, 300)" />
  <NODE NAME="N_B2" COORDINATE="(0, 200)" />
  <NODE NAME="N_B3" COORDINATE="(0, 20)" />

  <NODE NAME="N_C1" COORDINATE="(300, 0)" />
  <NODE NAME="N_C2" COORDINATE="(200, 0)" />
  <NODE NAME="N_C3" COORDINATE="(20, 0)" />

  <NODE NAME="N_D1" COORDINATE="(0, -300)" />
  <NODE NAME="N_D2" COORDINATE="(0, -200)" />
  <NODE NAME="N_D3" COORDINATE="(0, -20)" />

  <LINK NAME="L_A1-A2" NODESTART="N_A1" NODEEND="N_A2" ROADTYPE="RT1ln_ref-3">
    <STRAIGHT />
  </LINK>
  <LINK NAME="L_A2-A3" NODESTART="N_A2" NODEEND="N_A3" ROADTYPE="RT3ln_ref-2">
    <STRAIGHT />
  </LINK>
  <LINK NAME="L_A3-D3" NODESTART="N_A3" NODEEND="N_D3" ROADTYPE="RT1ln_ref0" OFFSETSTART="-12m" OFFSETEND="-9m">
    <BEZIER />
  </LINK>
  <LINK NAME="L_A3-C3" NODESTART="N_A3" NODEEND="N_C3" ROADTYPE="RT1ln_ref-3">
    <STRAIGHT />
  </LINK>
  <LINK NAME="L_A3-B3" NODESTART="N_A3" NODEEND="N_B3" ROADTYPE="RT1ln_ref0" OFFSETSTART="-6m" OFFSETEND="-9m"
    ROTATIONSTART="0 deg" ROTATIONEND="90 deg">
    <BEZIER />
  </LINK>

  <LINK NAME="L_C1-C2" NODESTART="N_C1" NODEEND="N_C2" ROADTYPE="RT1ln_ref-3">
    <STRAIGHT />
  </LINK>
  <LINK NAME="L_C2-C3" NODESTART="N_C2" NODEEND="N_C3" ROADTYPE="RT3ln_ref-2">
    <STRAIGHT />
  </LINK>
  <LINK NAME="L_B3_C3" NODESTART="N_B3" NODEEND="N_C3" ROADTYPE="RT1ln_ref0" OFFSETEND="-9m" OFFSETSTART="9m"
    ROTATIONSTART="270 deg" ROTATIONEND="0 deg">
    <BEZIER />
  </LINK>
  <LINK NAME="L_C3-A3" NODESTART="N_C3" NODEEND="N_A3" ROADTYPE="RT1ln_ref-3">
    <STRAIGHT />
  </LINK>
  <LINK NAME="L_D3_C3" NODESTART="N_D3" NODEEND="N_C3" ROADTYPE="RT1ln_ref0" OFFSETEND="-9m" OFFSETSTART="9m"
    ROTATIONSTART="90 deg" ROTATIONEND="0 deg">
    <BEZIER />
  </LINK>


  <LINK NAME="L_A3-A1" NODESTART="N_A3" NODEEND="N_A1" ROADTYPE="RT1ln_ref-3">
    <STRAIGHT />
  </LINK>
  <LINK NAME="L_B3-B1" NODESTART="N_B3" NODEEND="N_B1" ROADTYPE="RT1ln_ref-3">
    <STRAIGHT />
  </LINK>
  <LINK NAME="L_C3-C1" NODESTART="N_C3" NODEEND="N_C1" ROADTYPE="RT1ln_ref-3">
    <STRAIGHT />
  </LINK>
  <LINK NAME="L_D3-D1" NODESTART="N_D3" NODEEND="N_D1" ROADTYPE="RT1ln_ref-3">
    <STRAIGHT />
  </LINK>

</NETWORK>

=== averbraeck/opentrafficsim/trunk/ots-parser-xml/src/test/resources/offset-example.xml
<?xml version="1.0" encoding="UTF-8" ?>
<NETWORK xmlns="http://www.opentrafficsim.org/ots" xmlns:ots="http://www.opentrafficsim.org/ots" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.opentrafficsim.org/ots http://www.opentrafficsim.org/docs/current/ots-network.xsd" xmlns:xi="http://www.w3.org/2001/XInclude">

  <!-- fallback included to be able to run in eclipse -->
  <xi:include href="roadtypes.xml" parse="xml">
    <xi:fallback>
      <xi:include href="./target/classes/roadtypes.xml" parse="xml" />
    </xi:fallback>
  </xi:include>

  <DEFINITIONS>

    <GTU NAME="CAR" GTUTYPE="CAR" LENGTH="CONST(5) m" WIDTH="UNIF(1.7, 2) m"
      MAXSPEED="TRIA(50,80,120) km/h" />
    <GTU NAME="TRUCK" GTUTYPE="TRUCK" LENGTH="UNIF(16,24) m" WIDTH="UNIF(2.2, 2.7) m"
      MAXSPEED="CONST(100) km/h" />

    <GTUMIX NAME="C60T40">
      <GTU NAME="CAR" WEIGHT="60"></GTU>
      <GTU NAME="TRUCK" WEIGHT="40"></GTU>
    </GTUMIX>

    <GTUMIX NAME="C80T20">
      <GTU NAME="CAR" WEIGHT="80" />
      <GTU NAME="TRUCK" WEIGHT="20" />
    </GTUMIX>

  </DEFINITIONS>


  <NODE NAME="N1a" COORDINATE="(0.0, 0.0)" DIRECTION="90 deg" />
  <NODE NAME="N1b" />
  <NODE NAME="N2a" COORDINATE="(100.0, 0.0)" DIRECTION="90 deg" />
  <NODE NAME="N2b" />
  <NODE NAME="N3a" COORDINATE="(200.0, 0.0)" DIRECTION="90 deg" />
  <NODE NAME="N3b" />

  <LINK NAME="L1" NODESTART="N1a" NODEEND="N1b" ROADLAYOUT="r3">
    <STRAIGHT LENGTH="200m" />
  </LINK>

  <LINK NAME="L2" NODESTART="N2a" NODEEND="N2b" ROADLAYOUT="r3" OFFSETSTART="25m">
    <STRAIGHT LENGTH="200m" />
  </LINK>

  <LINK NAME="L3" NODESTART="N3a" NODEEND="N3b" ROADLAYOUT="r3" OFFSETSTART="50m" ROTATIONSTART="-90 deg">
    <STRAIGHT LENGTH="200m" />
  </LINK>

</NETWORK>
