=== averbraeck/opentrafficsim/trunk/ots-core/src/main/resources/ots-infra.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.opentrafficsim.org/ots-infra" xmlns="http://www.opentrafficsim.org/ots-infra"
	elementFormDefault="qualified">

	<xsd:simpleType name="SPEEDTYPE">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="\d+[\.]{0,1}\d*\s*(km/h|m/s|mi/h|y/s|ft/s)"></xsd:pattern>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="LENGTHTYPE">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="\d+[\.]{0,1}\d*\s*(mm|cm|dm|m|dam|hm|km|mi|y|ft)"></xsd:pattern>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="COORDINATETYPE">
		<xsd:restriction base="xsd:string">
			<xsd:pattern
				value="\(\s*(\-|\+){0,1}\d+[\.]{0,1}\d*\s*\,\s*(\-|\+){0,1}\d+[\.]{0,1}\d*(\s*,\s*(\-|\+){0,1}\d+[\.]{0,1}\d*){0,1}\)">
			</xsd:pattern>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="LEFTRIGHTTYPE">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="L|LEFT|R|RIGHT|CLOCKWISE|COUNTERCLOCKWISE"></xsd:pattern>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="ANGLETYPE">
		<xsd:restriction base="xsd:double">
			<xsd:minInclusive value="-180.0"></xsd:minInclusive>
			<xsd:maxInclusive value="180.0"></xsd:maxInclusive>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="ELEMENTSTYPE">
		<xsd:restriction base="xsd:string">
			<xsd:pattern
				value="((((S|X|V|A)\d+){0,10}(\||\:|\#|&lt;|&gt;){0,1}){0,10}D(((S|X|V|A)\d+){0,10}(\||\:|\#|&lt;|&gt;){0,1}){0,10})|((((S|X|V|A)\d+){0,10}(\||\:|\#|&lt;|&gt;){0,1}){0,10}((SD|XD|VD|AD)\d+)(((S|X|V|A)\d+){0,10}(\||\:|\#|&lt;|&gt;){0,1}){0,10})"></xsd:pattern>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:group name="NODELINK">
		<xsd:choice>
			<xsd:element name="NODE" minOccurs="1" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:attribute name="NAME" type="xsd:string" use="required"></xsd:attribute>
					<xsd:attribute name="COORDINATE" type="COORDINATETYPE"
						use="optional"></xsd:attribute>
					<xsd:attribute name="ANGLE" type="ANGLETYPE" use="optional"></xsd:attribute>
				</xsd:complexType>
			</xsd:element>

			<xsd:element name="LINK" minOccurs="1" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:choice>
							<xsd:element name="STRAIGHT">
								<xsd:complexType>
									<xsd:attribute name="LENGTH" type="LENGTHTYPE"
										use="required"></xsd:attribute>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="ARC">
								<xsd:complexType>
									<xsd:attribute name="RADIUS" type="LENGTHTYPE"
										use="required"></xsd:attribute>
									<xsd:attribute name="ANGLE" type="ANGLETYPE" use="required"></xsd:attribute>
									<xsd:attribute name="DIRECTION" type="LEFTRIGHTTYPE"
										use="required"></xsd:attribute>
								</xsd:complexType>
							</xsd:element>
						</xsd:choice>

						<xsd:element name="LANE" minOccurs="0" maxOccurs="unbounded">
							<xsd:complexType>
								<xsd:attribute name="NAME" type="xsd:string" use="required"></xsd:attribute>
								<xsd:attribute name="SPEED" type="SPEEDTYPE"></xsd:attribute>
								<xsd:attribute name="WIDTH" type="LENGTHTYPE"></xsd:attribute>
							</xsd:complexType>
						</xsd:element>
					</xsd:sequence>

					<xsd:attribute name="NAME" type="xsd:string" use="required"></xsd:attribute>
					<xsd:attribute name="FROM" type="xsd:string" use="required"></xsd:attribute>
					<xsd:attribute name="TO" type="xsd:string" use="required"></xsd:attribute>
					<xsd:attribute name="ELEMENTS" type="ELEMENTSTYPE"
						use="required"></xsd:attribute>
					<xsd:attribute name="SPEED" type="SPEEDTYPE"></xsd:attribute>
					<xsd:attribute name="WIDTH" type="LENGTHTYPE"></xsd:attribute>
				</xsd:complexType>
			</xsd:element>
		</xsd:choice>
	</xsd:group>

	<xsd:element name="NETWORK">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="GLOBAL" minOccurs="0" maxOccurs="1">
					<xsd:complexType>
						<xsd:attribute name="SPEED" type="SPEEDTYPE"></xsd:attribute>
						<xsd:attribute name="WIDTH" type="LENGTHTYPE"></xsd:attribute>
					</xsd:complexType>
				</xsd:element>

				<xsd:element name="GTU" minOccurs="0" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:attribute name="NAME" type="xsd:string" use="required"></xsd:attribute>
					</xsd:complexType>
				</xsd:element>

				<xsd:group ref="NODELINK" minOccurs="1" maxOccurs="unbounded" />

			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== averbraeck/opentrafficsim/trunk/ots-core/src/main/resources/ots-infra-example.xml
<?xml version="1.0" encoding="UTF-8"?>
<NETWORK xmlns="http://www.example.org/ots-infra" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/ots-infra ots-infra.xsd ">

	<GLOBAL WIDTH="3.6m" SPEED="80km/h" />

	<NODE NAME="N1" COORDINATE="(0.0, -10.0)" />
	<NODE NAME="N2" />

	<LINK NAME="A4_12" FROM="N1" TO="N2" ELEMENTS="X1|V2:V1|D|A1:A2|X2">
		<STRAIGHT LENGTH="50m" />
		<LANE NAME="X1" WIDTH="1m" />
		<LANE NAME="X2" WIDTH="1m" />
	</LINK>

	<NODE NAME="N3b2" />

	<LINK NAME="A4_13" FROM="N2" TO="N3b2" ELEMENTS="X1|V2:V1|D|A1:A2|X2">
		<ARC RADIUS="100m" ANGLE="90" />
		<LANE NAME="X1" WIDTH="1m" />
		<LANE NAME="X2" WIDTH="1m" />
	</LINK>

	<NODE NAME="N4" />

	<LINK NAME="A4_14" FROM="N3b2" TO="N4" ELEMENTS="X1|V2:V1|D|A1:A2|:A3|X2">
		<STRAIGHT LENGTH="50m" />
		<LANE NAME="X1" WIDTH="1m" />
		<LANE NAME="X2" WIDTH="1m" />
		<LANE NAME="A3" SPEED="60km/h" />
	</LINK>

	<NODE NAME="N5" />
	<NODE NAME="ENTRY5" />

	<LINK NAME="A4_15" FROM="N4" TO="N5" ELEMENTS="X1|V2:V1|D|A1:A2|X2">
		<STRAIGHT LENGTH="100m" />
		<LANE NAME="X1" WIDTH="1m" />
		<LANE NAME="X2" WIDTH="1m" />
	</LINK>

	<LINK NAME="LE1" FROM="ENTRY5" TO="N3b2" ELEMENTS="|A|" SPEED="60km/h">
		<ARC RADIUS="100m" ANGLE="-45" />
	</LINK>

	<NODE NAME="ENTRY6" />
	<LINK NAME="LE2" FROM="ENTRY6" TO="ENTRY5" ELEMENTS="|A|" SPEED="60km/h">
		<ARC RADIUS="100m" ANGLE="45" />
	</LINK>

</NETWORK>

=== averbraeck/opentrafficsim/trunk/ots-core/src/main/resources/circular-road-gtu-example.xml
<?xml version="1.0" encoding="UTF-8"?>
<NETWORK xmlns="http://www.opentrafficsim.org/ots-infra" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.opentrafficsim.org/ots-infra ots-infra.xsd">

  <GLOBAL WIDTH="3.6m" SPEED="100km/h" />

  <!-- extent -->
  <!-- seeds -->

  <GTU NAME="CAR" GTUTYPE="CAR" FOLLOWING="IDM+" LENGTH="UNIF(5,7) m" WIDTH="UNIF(1.7, 2) m" LANECHANGE="EGOISTIC"
    MAXSPEED="CONST(120) km/h" />
  <GTU NAME="TRUCK" GTUTYPE="TRUCK" FOLLOWING="IDM+" LENGTH="UNIF(16,24) m" WIDTH="UNIF(2.2, 2.7) m" LANECHANGE="ALTRUISTIC"
    MAXSPEED="CONST(100) km/h" />

  <ROUTE NAME="CIRCLE" NODELIST="NE N1 N2 N1" />
  
  <GTUMIX NAME="C60T40">
    <GTU NAME="CAR" WEIGHT="60"></GTU>
    <GTU NAME="TRUCK" WEIGHT="40"></GTU>
  </GTUMIX>

  <NODE NAME="N1" COORDINATE="(0.0, 0.0)" ANGLE="90" />
  <NODE NAME="N2" />
  <NODE NAME="NE" />

  <LINK NAME="L1" FROM="N1" TO="N2" ELEMENTS="S1-X1|A1:D:A2|X2-S2">
    <ARC RADIUS="1000m" ANGLE="180" DIRECTION="L" />
    <LANE NAME="X1" WIDTH="2.5m" />
    <LANE NAME="X2" WIDTH="2.5m" />
    <LANE NAME="S1" WIDTH="2m" />
    <LANE NAME="S2" WIDTH="2m" />
  </LINK>

  <LINK NAME="L2" FROM="N2" TO="N1" ELEMENTS="S1-X1|A1:D:A2|X2-S2">
    <ARC RADIUS="1000m" ANGLE="180" DIRECTION="L" />
    <LANE NAME="X1" WIDTH="2.5m" />
    <LANE NAME="X2" WIDTH="2.5m" />
    <LANE NAME="S1" WIDTH="2m" />
    <LANE NAME="S2" WIDTH="2m" />
  </LINK>

  <GTUMIX NAME="C80T20">
    <GTU NAME="CAR" WEIGHT="80" />
    <GTU NAME="TRUCK" WEIGHT="20" />
  </GTUMIX>

  <LINK NAME="ENTRY" FROM="NE" TO="N1" ELEMENTS="S1-X1|A1:D:A2|X2-S2">
    <STRAIGHT LENGTH="200m" />
    <LANE NAME="A1" SPEED="100 km/h" />
    <LANE NAME="X1" WIDTH="2.5m" />
    <LANE NAME="X2" WIDTH="2.5m" />
    <LANE NAME="S1" WIDTH="2m" />
    <LANE NAME="S2" WIDTH="2m" />
    <GENERATOR LANE="A1" IAT="EXPO(30) s" INITIALSPEED="TRIA(80,90,100) km/h" MAXGTU="50" GTU="CAR" ROUTE="CIRCLE" />
    <GENERATOR LANE="A2" IAT="EXPO(45) s" INITIALSPEED="TRIA(80,90,100) km/h" MAXGTU="25" GTU="CAR" ROUTE="CIRCLE" />
  </LINK>

</NETWORK>

=== averbraeck/opentrafficsim/trunk/ots-core/src/main/resources/circular-road-example.xml
<?xml version="1.0" encoding="UTF-8"?>
<NETWORK xmlns="http://www.opentrafficsim.org/ots-infra"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.opentrafficsim.org/ots-infra ots-infra.xsd">

	<GLOBAL WIDTH="3.6m" SPEED="80km/h" />

	<NODE NAME="N1" COORDINATE="(0.0, 0.0)" ANGLE="90" />
	<NODE NAME="N2" />
	<NODE NAME="NE" />

	<LINK NAME="L1" FROM="N1" TO="N2" ELEMENTS="A1:D:A2">
		<ARC RADIUS="1000m" ANGLE="180" DIRECTION="L" />
	</LINK>

	<LINK NAME="L2" FROM="N2" TO="N1" ELEMENTS="A1:D:A2">
		<ARC RADIUS="1000m" ANGLE="180" DIRECTION="L" />
	</LINK>

	<LINK NAME="ENTRY" FROM="NE" TO="N1" ELEMENTS="A1:D:A2">
		<STRAIGHT LENGTH="200m" />
	</LINK>

</NETWORK>
