=== averbraeck/opentrafficsim/release/1.04.04/ots-xsd/src/main/resources/xsd/1.04.01/ots-network.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.opentrafficsim.org/ots"
  xmlns:ots="http://www.opentrafficsim.org/ots" xmlns="http://www.opentrafficsim.org/ots"
  xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  elementFormDefault="qualified">

  <!-- http://www.w3.org/2009/01/xml.xsd -->
  <xsd:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="../ref/xml.xsd" />
  <!-- http://www.w3.org/2001/xinclude.xsd -->
  <xsd:import namespace="http://www.w3.org/2001/XInclude" schemaLocation="../ref/xinclude.xsd" />

  <xsd:include schemaLocation="ots-definitions.xsd" />
  <xsd:include schemaLocation="ots-control.xsd" />

  <!-- https://opentrafficsim.org/docs/xsd/version/ots-definitions.xsd -->

  <!-- ================================================================================================== -->
  <!-- ================================================ NETWORK ========================================= -->
  <!-- ================================================================================================== -->

  <xsd:element name="NODE">
    <xsd:complexType>
      <xsd:attribute name="ID" type="xsd:string" use="required" />
      <xsd:attribute name="COORDINATE" type="COORDINATETYPE" use="required" />
      <xsd:attribute name="DIRECTION" type="DIRECTIONTYPE" use="optional" />
      <xsd:attribute ref="xml:base" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="CONNECTOR">
    <xsd:complexType>
      <xsd:attribute name="ID" type="xsd:string" use="required" />
      <xsd:attribute name="NODESTART" type="xsd:string" use="required" />
      <xsd:attribute name="NODEEND" type="xsd:string" use="required" />
      <xsd:attribute name="DEMANDWEIGHT" type="FRACTIONTYPE" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="LINK">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:choice>
          <xsd:element name="STRAIGHT" />
          <xsd:element name="BEZIER">
            <xsd:complexType>
              <xsd:attribute name="STARTDIRECTION" type="DIRECTIONTYPE" use="optional" />
              <xsd:attribute name="ENDDIRECTION" type="DIRECTIONTYPE" use="optional" />
              <xsd:attribute name="NUMSEGMENTS" type="xsd:integer" use="optional" default="64" />
              <xsd:attribute name="SHAPE" type="POSITIVEDOUBLE" use="optional" default="1.0" />
              <xsd:attribute name="WEIGHTED" type="xsd:boolean" use="optional" default="false" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="CLOTHOID">
            <xsd:complexType>
              <xsd:attribute name="STARTDIRECTION" type="DIRECTIONTYPE" use="optional" />
              <xsd:attribute name="STARTCURVATURE" type="PERLENGTHTYPE" use="required" />
              <xsd:attribute name="ENDDIRECTION" type="DIRECTIONTYPE" use="optional" />
              <xsd:attribute name="ENDCURVATURE" type="PERLENGTHTYPE" use="required" />
              <xsd:attribute name="LENGTH" type="POSITIVELENGTHTYPE" use="optional" />
              <xsd:attribute name="ENDELEVATION" type="POSITIVELENGTHTYPE" use="optional" />
              <xsd:attribute name="NUMSEGMENTS" type="xsd:integer" use="optional" default="64" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="ARC">
            <xsd:complexType>
              <xsd:attribute name="RADIUS" type="POSITIVELENGTHTYPE" use="required" />
              <xsd:attribute name="DIRECTION" type="LEFTRIGHTTYPE" use="required" />
              <xsd:attribute name="NUMSEGMENTS" type="xsd:integer" use="optional" default="64" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="POLYLINE">
            <xsd:complexType>
              <!-- Not necessary to specify the points on the two nodes. -->
              <xsd:sequence minOccurs="1" maxOccurs="unbounded">
                <xsd:element name="COORDINATE" type="COORDINATETYPE" />
              </xsd:sequence>
            </xsd:complexType>
          </xsd:element>
        </xsd:choice>

        <xsd:choice>
          <xsd:element name="ROADLAYOUT">
            <xsd:complexType>
              <xsd:complexContent>
                <xsd:extension base="BASICROADLAYOUT">
                </xsd:extension>
              </xsd:complexContent>
            </xsd:complexType>
          </xsd:element>
          <xsd:sequence>
            <xsd:element name="DEFINEDLAYOUT" type="xsd:string" />
            <xsd:element name="LANEOVERRIDE" minOccurs="0" maxOccurs="unbounded">
              <xsd:complexType>
                <xsd:sequence>
                  <xsd:element ref="SPEEDLIMIT" minOccurs="0" maxOccurs="unbounded" />
                </xsd:sequence>
                <xsd:attribute name="LANE" type="xsd:string" use="required" />
              </xsd:complexType>
            </xsd:element>
          </xsd:sequence>
        </xsd:choice>

        <xsd:element name="TRAFFICLIGHT" type="TRAFFICLIGHTTYPE" minOccurs="0" maxOccurs="unbounded" />
        <xsd:element name="TRAFFICLIGHTSENSOR" type="TRAFFICLIGHTSENSORTYPE" minOccurs="0"
          maxOccurs="unbounded" />

      </xsd:sequence>

      <xsd:attribute name="ID" type="xsd:string" use="required" />
      <xsd:attribute name="TYPE" type="xsd:string" use="required" />
      <xsd:attribute name="NODESTART" type="xsd:string" use="required" />
      <xsd:attribute name="NODEEND" type="xsd:string" use="required" />
      <xsd:attribute name="OFFSETSTART" type="LENGTHTYPE" use="optional" default="0.0 m" />
      <xsd:attribute name="OFFSETEND" type="LENGTHTYPE" use="optional" default="0.0 m" />
      <xsd:attribute name="LANEKEEPING" type="LANEKEEPINGTYPE" use="optional" default="KEEPRIGHT" />
      <xsd:attribute name="PRIORITY" type="PRIORITYTYPE" use="optional" />
      <xsd:attribute name="FIXGRADUALOFFSET" type="xsd:boolean" use="optional" default="false" />
      <xsd:attribute name="CONFLICTID" type="xsd:string" use="optional" />
      <xsd:attribute ref="xml:base" />
    </xsd:complexType>
  </xsd:element>


  <xsd:element name="NETWORK">
    <xsd:complexType>
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="xi:include" minOccurs="0" maxOccurs="1" />
        <xsd:element ref="NODE" minOccurs="0" maxOccurs="1" />
        <xsd:element ref="CONNECTOR" minOccurs="0" maxOccurs="1" />
        <xsd:element ref="LINK" minOccurs="0" maxOccurs="1" />
      </xsd:choice>
      <xsd:attribute ref="xml:base" />
    </xsd:complexType>
  </xsd:element>

  <!-- ================================================================================================== -->
  <!-- ================================================= TYPES ========================================== -->
  <!-- ================================================================================================== -->

  <!-- LINK plus TRAFFICLIGHT.ID should be unique. -->

  <xsd:complexType name="TRAFFICLIGHTTYPE">
    <xsd:attribute name="ID" type="xsd:string" use="required" />
    <xsd:attribute name="LANE" type="xsd:string" use="required" />
    <xsd:attribute name="POSITION" type="LENGTHBEGINENDTYPE" use="required" />
    <xsd:attribute name="CLASS" type="CLASSNAMETYPE" use="required">
      <xsd:annotation>
        <xsd:documentation source="description">
          Fully specified classname including the package.
        </xsd:documentation>
      </xsd:annotation>
    </xsd:attribute>
  </xsd:complexType>

  <xsd:complexType name="TRAFFICLIGHTSENSORTYPE">
    <xsd:attribute name="ID" type="xsd:string" use="required" />
    <xsd:attribute name="LANE" type="xsd:string" use="required" />
    <xsd:attribute name="POSITION" type="LENGTHBEGINENDTYPE" use="required" />
    <xsd:attribute name="LENGTH" type="POSITIVELENGTHTYPE" use="required" />
    <!-- TODO allow for detectors that span multiple lanes (longitudinally); thus multiple links -->
    <xsd:attribute name="CLASS" type="CLASSNAMETYPE" use="required">
      <xsd:annotation>
        <xsd:documentation source="description">
          Fully specified classname including the package.
        </xsd:documentation>
      </xsd:annotation>
    </xsd:attribute>
  </xsd:complexType>

</xsd:schema>

=== averbraeck/opentrafficsim/release/1.00.01/ots-parser-xml/src/test/resources/Testnetwork2.x.xml
<?xml version="1.0" encoding="UTF-8" ?>
<NETWORK xmlns="http://www.opentrafficsim.org/ots" xmlns:ots="http://www.opentrafficsim.org/ots" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.opentrafficsim.org/ots http://www.opentrafficsim.org/docs/current/ots-network.xsd" xmlns:xi="http://www.w3.org/2001/XInclude">

  <DEFINITIONS>

    <GLOBAL />

    <GTUTYPE NAME="CAR" />

    <GTU NAME="CAR" GTUTYPE="CAR" LENGTH="CONST(4.5) m" WIDTH="CONST(2) m"
      MAXSPEED="CONST(80) km/h" />

    <ROADTYPE NAME="HIGHWAY" DEFAULTLANEWIDTH="3m" DEFAULTOVERTAKING="NONE" DEFAULTLANEKEEPING="KEEPLANE">
      <SPEEDLIMIT GTUTYPE="CAR" LEGALSPEEDLIMIT="120 km/h"/>
    </ROADTYPE>

    <ROADLAYOUT NAME="RT1ln_ref-4" ROADTYPE="HIGHWAY">
      <LANE NAME="A1" OFFSET="-12m" WIDTH="3m" DIRECTION="FORWARD" />
    </ROADLAYOUT>

    <ROADLAYOUT NAME="RT1ln_ref-3" ROADTYPE="HIGHWAY">
      <LANE NAME="A1" OFFSET="-9m" WIDTH="3m" DIRECTION="FORWARD" />
    </ROADLAYOUT>

    <ROADLAYOUT NAME="RT1ln_ref-2" ROADTYPE="HIGHWAY">
      <LANE NAME="A1" OFFSET="-6m" WIDTH="3m" DIRECTION="FORWARD" />
    </ROADLAYOUT>

    <ROADLAYOUT NAME="RT1ln_ref0" ROADTYPE="HIGHWAY">
      <LANE NAME="A1" OFFSET="0m" WIDTH="3m" DIRECTION="FORWARD" />
    </ROADLAYOUT>

    <ROADLAYOUT NAME="RT3ln_ref-2" ROADTYPE="HIGHWAY">
      <LANE NAME="A1" OFFSET="-12m" WIDTH="3m" DIRECTION="FORWARD" />
      <STRIPE TYPE="DASHED" OFFSET="-10.5m" />
      <LANE NAME="A2" OFFSET="-9m" WIDTH="3m" DIRECTION="FORWARD" />
      <STRIPE TYPE="DASHED" OFFSET="-7.5m" />
      <LANE NAME="A3" OFFSET="-6m" WIDTH="3m" DIRECTION="FORWARD" />
    </ROADLAYOUT>

  </DEFINITIONS>

  <NODE NAME="N_A1" COORDINATE="(-300, 0)" ANGLE="0 deg" />
  <NODE NAME="N_A2" COORDINATE="(-200, 0)" />
  <NODE NAME="N_A3" COORDINATE="(-20, 0)" />

  <NODE NAME="N_B1" COORDINATE="(0, 300)" />
  <NODE NAME="N_B2" COORDINATE="(0, 200)" />
  <NODE NAME="N_B3" COORDINATE="(0, 20)" />

  <NODE NAME="N_C1" COORDINATE="(300, 0)" />
  <NODE NAME="N_C2" COORDINATE="(200, 0)" />
  <NODE NAME="N_C3" COORDINATE="(20, 0)" />

  <NODE NAME="N_D1" COORDINATE="(0, -300)" />
  <NODE NAME="N_D2" COORDINATE="(0, -200)" />
  <NODE NAME="N_D3" COORDINATE="(0, -20)" />

  <LINK NAME="L_A1-A2" NODESTART="N_A1" NODEEND="N_A2" ROADLAYOUT="RT1ln_ref-3">
    <STRAIGHT />
  </LINK>
  <LINK NAME="L_A2-A3" NODESTART="N_A2" NODEEND="N_A3" ROADLAYOUT="RT3ln_ref-2">
    <STRAIGHT />
  </LINK>
  <LINK NAME="L_A3-D3" NODESTART="N_A3" NODEEND="N_D3" ROADLAYOUT="RT1ln_ref0" OFFSETSTART="-12m" OFFSETEND="-9m">
    <BEZIER />
  </LINK>
  <LINK NAME="L_A3-C3" NODESTART="N_A3" NODEEND="N_C3" ROADLAYOUT="RT1ln_ref-3">
    <STRAIGHT />
  </LINK>
  <LINK NAME="L_A3-B3" NODESTART="N_A3" NODEEND="N_B3" ROADLAYOUT="RT1ln_ref0" OFFSETSTART="-6m" OFFSETEND="-9m"
    ROTATIONSTART="0 deg" ROTATIONEND="90 deg">
    <BEZIER />
  </LINK>

  <LINK NAME="L_C1-C2" NODESTART="N_C1" NODEEND="N_C2" ROADLAYOUT="RT1ln_ref-3">
    <STRAIGHT />
  </LINK>
  <LINK NAME="L_C2-C3" NODESTART="N_C2" NODEEND="N_C3" ROADLAYOUT="RT3ln_ref-2">
    <STRAIGHT />
  </LINK>
  <LINK NAME="L_B3_C3" NODESTART="N_B3" NODEEND="N_C3" ROADLAYOUT="RT1ln_ref0" OFFSETEND="-9m" OFFSETSTART="9m"
    ROTATIONSTART="270 deg" ROTATIONEND="0 deg">
    <BEZIER />
  </LINK>
  <LINK NAME="L_C3-A3" NODESTART="N_C3" NODEEND="N_A3" ROADLAYOUT="RT1ln_ref-3">
    <STRAIGHT />
  </LINK>
  <LINK NAME="L_D3_C3" NODESTART="N_D3" NODEEND="N_C3" ROADLAYOUT="RT1ln_ref0" OFFSETEND="-9m" OFFSETSTART="9m"
    ROTATIONSTART="90 deg" ROTATIONEND="0 deg">
    <BEZIER />
  </LINK>


  <LINK NAME="L_A3-A1" NODESTART="N_A3" NODEEND="N_A1" ROADLAYOUT="RT1ln_ref-3">
    <STRAIGHT />
  </LINK>
  <LINK NAME="L_B3-B1" NODESTART="N_B3" NODEEND="N_B1" ROADLAYOUT="RT1ln_ref-3">
    <STRAIGHT />
  </LINK>
  <LINK NAME="L_C3-C1" NODESTART="N_C3" NODEEND="N_C1" ROADLAYOUT="RT1ln_ref-3">
    <STRAIGHT />
  </LINK>
  <LINK NAME="L_D3-D1" NODESTART="N_D3" NODEEND="N_D1" ROADLAYOUT="RT1ln_ref-3">
    <STRAIGHT />
  </LINK>

</NETWORK>
