=== averbraeck/opentrafficsim/trunk/ots-xsd/src/main/resources/xsd/1.01.02/ots-definitions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.opentrafficsim.org/ots"
  xmlns:ots="http://www.opentrafficsim.org/ots" xmlns="http://www.opentrafficsim.org/ots" xmlns:xi="http://www.w3.org/2001/XInclude"
  xmlns:fn="http://www.w3.org/2005/xpath-functions" elementFormDefault="qualified">

  <!-- http://www.w3.org/2009/01/xml.xsd -->
  <xsd:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="../ref/xml.xsd" />
  <!-- http://www.w3.org/2001/xinclude.xsd -->
  <xsd:import namespace="http://www.w3.org/2001/XInclude" schemaLocation="../ref/xinclude.xsd" />

  <xsd:include schemaLocation="ots-types.xsd" />

  <!-- ================================================================================================== -->
  <!-- =============================================== ELEMENTS ========================================= -->
  <!-- ================================================================================================== -->

  <xsd:element name="GTUTYPE">
    <xsd:complexType>
      <xsd:attribute name="ID" type="xsd:string" use="required" />
      <xsd:attribute name="PARENT" type="xsd:string" use="optional" />
      <xsd:attribute name="DEFAULT" type="xsd:boolean" use="optional" default="false" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="GTUTYPES">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="GTUTYPE" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attribute ref="xml:base" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="GTUTEMPLATE">
    <xsd:complexType>
      <xsd:attribute name="ID" type="xsd:string" use="required" />
      <xsd:attribute name="GTUTYPE" type="xsd:string" use="required" />
      <xsd:attribute name="LENGTHDIST" type="LENGTHDISTTYPE" use="required" />
      <xsd:attribute name="WIDTHDIST" type="LENGTHDISTTYPE" use="required" />
      <xsd:attribute name="MAXSPEEDDIST" type="SPEEDDISTTYPE" use="required" />
      <xsd:attribute name="MAXACCELERATIONDIST" type="ACCELERATIONDISTTYPE" use="optional" default="CONST(3.0) m/s^2" />
      <xsd:attribute name="MAXDECELERATIONDIST" type="ACCELERATIONDISTTYPE" use="optional" default="CONST(8.0) m/s^2" />
      <xsd:attribute name="DEFAULT" type="xsd:boolean" use="optional" default="false" />
      <xsd:attribute ref="xml:base" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="GTUTEMPLATES">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="GTUTEMPLATE" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attribute ref="xml:base" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="COMPATIBILITY">
    <xsd:complexType>
      <xsd:attribute name="GTUTYPE" type="xsd:string" use="required" />
      <xsd:attribute name="DIRECTION" type="DRIVINGDIRECTIONTYPE" use="optional" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="LANETYPE">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="COMPATIBILITY" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attribute name="ID" type="xsd:string" use="required" />
      <xsd:attribute name="PARENT" type="xsd:string" use="optional" />
      <xsd:attribute name="DEFAULT" type="xsd:boolean" use="optional" default="false" />
      <xsd:attribute ref="xml:base" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="LANETYPES">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="LANETYPE" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attribute ref="xml:base" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="LINKTYPE">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="COMPATIBILITY" minOccurs="0" maxOccurs="unbounded" />
        <xsd:element ref="SPEEDLIMIT" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attribute name="ID" type="xsd:string" use="required" />
      <xsd:attribute name="PARENT" type="xsd:string" use="optional" />
      <xsd:attribute name="DEFAULT" type="xsd:boolean" use="optional" default="false" />
      <xsd:attribute ref="xml:base" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="LINKTYPES">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="LINKTYPE" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attribute ref="xml:base" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="SPEEDLIMIT">
    <xsd:complexType>
      <xsd:attribute name="GTUTYPE" type="xsd:string" use="required" />
      <xsd:attribute name="LEGALSPEEDLIMIT" type="SPEEDTYPE" use="optional" />
    </xsd:complexType>
  </xsd:element>

  <xsd:complexType name="CROSSSECTIONELEMENT">
    <xsd:sequence>
      <xsd:choice minOccurs="0">
        <xsd:element name="CENTEROFFSET" type="SIGNEDLENGTHTYPE" />
        <xsd:element name="LEFTOFFSET" type="SIGNEDLENGTHTYPE" />
        <xsd:element name="RIGHTOFFSET" type="SIGNEDLENGTHTYPE" />
        <xsd:sequence>
          <xsd:choice>
            <xsd:element name="CENTEROFFSETSTART" type="SIGNEDLENGTHTYPE" />
            <xsd:element name="LEFTOFFSETSTART" type="SIGNEDLENGTHTYPE" />
            <xsd:element name="RIGHTOFFSETSTART" type="SIGNEDLENGTHTYPE" />
          </xsd:choice>
          <xsd:choice>
            <xsd:element name="CENTEROFFSETEND" type="SIGNEDLENGTHTYPE" />
            <xsd:element name="LEFTOFFSETEND" type="SIGNEDLENGTHTYPE" />
            <xsd:element name="RIGHTOFFSETEND" type="SIGNEDLENGTHTYPE" />
          </xsd:choice>
        </xsd:sequence>
      </xsd:choice>
      <xsd:choice>
        <xsd:element name="WIDTH" type="LENGTHTYPE" />
        <xsd:sequence>
          <xsd:element name="WIDTHSTART" type="SIGNEDLENGTHTYPE" />
          <xsd:element name="WIDTHEND" type="SIGNEDLENGTHTYPE" />
        </xsd:sequence>
      </xsd:choice>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="CSELANE">
    <xsd:complexContent>
      <xsd:extension base="CROSSSECTIONELEMENT">
        <xsd:sequence>
          <xsd:element ref="SPEEDLIMIT" minOccurs="0" maxOccurs="unbounded" />
        </xsd:sequence>
        <xsd:attribute name="ID" type="xsd:string" use="required" />
        <xsd:attribute name="LANETYPE" type="xsd:string" use="required" />
        <xsd:attribute name="DESIGNDIRECTION" type="xsd:boolean" use="required" />
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="CSENOTRAFFICLANE">
    <xsd:complexContent>
      <xsd:extension base="CROSSSECTIONELEMENT">
        <xsd:attribute name="ID" type="xsd:string" use="optional" />
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="CSESHOULDER">
    <xsd:complexContent>
      <xsd:extension base="CROSSSECTIONELEMENT">
        <xsd:attribute name="ID" type="xsd:string" use="optional" />
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="CSESTRIPE">
    <xsd:sequence>
      <xsd:choice minOccurs="0">
        <xsd:element name="CENTEROFFSET" type="SIGNEDLENGTHTYPE" />
        <xsd:element name="LEFTOFFSET" type="SIGNEDLENGTHTYPE" />
        <xsd:element name="RIGHTOFFSET" type="SIGNEDLENGTHTYPE" />
        <xsd:sequence>
          <xsd:choice>
            <xsd:element name="CENTEROFFSETSTART" type="SIGNEDLENGTHTYPE" />
            <xsd:element name="LEFTOFFSETSTART" type="SIGNEDLENGTHTYPE" />
            <xsd:element name="RIGHTOFFSETSTART" type="SIGNEDLENGTHTYPE" />
          </xsd:choice>
          <xsd:choice>
            <xsd:element name="CENTEROFFSETEND" type="SIGNEDLENGTHTYPE" />
            <xsd:element name="LEFTOFFSETEND" type="SIGNEDLENGTHTYPE" />
            <xsd:element name="RIGHTOFFSETEND" type="SIGNEDLENGTHTYPE" />
          </xsd:choice>
        </xsd:sequence>
      </xsd:choice>
      <xsd:element name="WIDTH" type="LENGTHTYPE" minOccurs="0" maxOccurs="1" />
    </xsd:sequence>
    <xsd:attribute name="ID" type="xsd:string" use="optional" />
    <xsd:attribute name="TYPE" type="STRIPETYPE" use="required" />
  </xsd:complexType>

  <xsd:element name="ROADLAYOUTS">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="ROADLAYOUT" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attribute ref="xml:base" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="ROADLAYOUT">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:sequence minOccurs="1" maxOccurs="unbounded">
          <xsd:choice>
            <xsd:element name="LANE" type="CSELANE" minOccurs="0" maxOccurs="unbounded" />
            <xsd:element name="NOTRAFFICLANE" type="CSENOTRAFFICLANE" minOccurs="0" maxOccurs="unbounded" />
            <xsd:element name="SHOULDER" type="CSESHOULDER" minOccurs="0" maxOccurs="unbounded" />
            <xsd:element name="STRIPE" type="CSESTRIPE" minOccurs="0" maxOccurs="unbounded" />
          </xsd:choice>
        </xsd:sequence>
        <xsd:element ref="SPEEDLIMIT" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attribute name="ID" type="xsd:string" use="required" />
      <xsd:attribute name="LINKTYPE" type="xsd:string" use="required" />
      <xsd:attribute name="LANEKEEPING" type="LANEKEEPINGTYPE" use="optional" />
      <xsd:attribute ref="xml:base" />
    </xsd:complexType>
  </xsd:element>

  <!-- ================================================================================================== -->
  <!-- ============================================== DEFINITIONS ======================================= -->
  <!-- ================================================================================================== -->

  <xsd:element name="DEFINITIONS">
    <xsd:complexType>
      <xsd:sequence minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="xi:include" minOccurs="0" maxOccurs="unbounded" />
        <xsd:element ref="GTUTYPES" minOccurs="0" maxOccurs="unbounded" />
        <xsd:element ref="GTUTEMPLATES" minOccurs="0" maxOccurs="unbounded" />
        <xsd:element ref="LINKTYPES" minOccurs="0" maxOccurs="unbounded" />
        <xsd:element ref="LANETYPES" minOccurs="0" maxOccurs="unbounded" />
        <xsd:element ref="ROADLAYOUTS" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attribute ref="xml:base" />
    </xsd:complexType>
  </xsd:element>

</xsd:schema>

=== averbraeck/opentrafficsim/trunk/ots-xsd/src/main/resources/xsd/1.04.01/defaults/default_gtutypes.xml
<?xml version="1.0" encoding="UTF-8"?>
<GTUTYPES xmlns="http://www.opentrafficsim.org/ots" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.opentrafficsim.org/ots ../ots-definitions.xsd
  http://www.opentrafficsim.org/ots https://opentrafficsim.org/docs/xsd/1.03.00/ots-definitions.xsd">

<!--
        ROAD_USER = new GTUType("ROAD_USER", null);
        WATERWAY_USER = new GTUType("WATERWAY_USER", null);
        RAILWAY_USER = new GTUType("RAILWAY_USER", null);

        SHIP = new GTUType("SHIP", WATERWAY_USER);
        TRAIN = new GTUType("TRAIN", RAILWAY_USER);
        PEDESTRIAN = new GTUType("PEDESTRIAN", ROAD_USER);
        BICYCLE = new GTUType("BICYCLE", ROAD_USER);
        MOPED = new GTUType("MOPED", BICYCLE);

        VEHICLE = new GTUType("VEHICLE", ROAD_USER);
        EMERGENCY_VEHICLE = new GTUType("EMERGENCY_VEHICLE", VEHICLE);
        CAR = new GTUType("CAR", VEHICLE);
        VAN = new GTUType("VAN", VEHICLE);
        BUS = new GTUType("BUS", VEHICLE);
        TRUCK = new GTUType("TRUCK", VEHICLE);
        SCHEDULED_BUS = new GTUType("SCHEDULED BUS", BUS); 
 -->

  <GTUTYPE ID="NONE" DEFAULT="true" />

  <GTUTYPE ID="ROAD_USER" DEFAULT="true" />
  <GTUTYPE ID="WATERWAY_USER" DEFAULT="true" />
  <GTUTYPE ID="RAILWAY_USER" DEFAULT="true" />
  
  <GTUTYPE ID="SHIP" PARENT="WATERWAY_USER" DEFAULT="true" />
  <GTUTYPE ID="TRAIN" PARENT="RAILWAY_USER" DEFAULT="true" />
  <GTUTYPE ID="PEDESTRIAN" PARENT="ROAD_USER" DEFAULT="true" />
  <GTUTYPE ID="BICYCLE" PARENT="ROAD_USER" DEFAULT="true" />
  <GTUTYPE ID="MOPED" PARENT="BICYCLE" DEFAULT="true" />
  
  <GTUTYPE ID="VEHICLE" PARENT="ROAD_USER" DEFAULT="true" />
  <GTUTYPE ID="EMERGENCY_VEHICLE" PARENT="VEHICLE" DEFAULT="true" />
  <GTUTYPE ID="CAR" PARENT="VEHICLE" DEFAULT="true" />
  <GTUTYPE ID="VAN" PARENT="VEHICLE" DEFAULT="true" />
  <GTUTYPE ID="BUS" PARENT="VEHICLE" DEFAULT="true" />
  <GTUTYPE ID="TRUCK" PARENT="VEHICLE" DEFAULT="true" />
  <GTUTYPE ID="SCHEDULED_BUS" PARENT="BUS" DEFAULT="true" />

</GTUTYPES>

=== averbraeck/opentrafficsim/trunk/ots-xsd/src/main/resources/xsd/1.01.02/defaults/default_linktypes.xml
<?xml version="1.0" encoding="UTF-8" ?>
<ots:LINKTYPES xmlns:ots="http://www.opentrafficsim.org/ots" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:schemaLocation="http://www.opentrafficsim.org/ots ../ots-definitions.xsd
  http://www.opentrafficsim.org/ots https://opentrafficsim.org/docs/xsd/1.01.02/ots-definitions.xsd">
  
  <!-- 
    GTUCompatibility<LinkType> compatibility = new GTUCompatibility<>((LinkType) null); 
    NONE = new LinkType("NONE", null, compatibility); 
    // 
    compatibility = new GTUCompatibility<>((LinkType) null); 
    compatibility.addAllowedGTUType(GTUType.ROAD_USER, LongitudinalDirectionality.DIR_BOTH); 
    ROAD = new LinkType("ROAD", null, compatibility); 
    // 
    compatibility = new GTUCompatibility<>((LinkType) null); 
    compatibility.addAllowedGTUType(GTUType.ROAD_USER, LongitudinalDirectionality.DIR_PLUS); 
    compatibility.addAllowedGTUType(GTUType.PEDESTRIAN, LongitudinalDirectionality.DIR_NONE); 
    compatibility.addAllowedGTUType(GTUType.BICYCLE, LongitudinalDirectionality.DIR_NONE); 
    FREEWAY = new LinkType("FREEWAY", ROAD, compatibility); 
    // 
    compatibility = new GTUCompatibility<>((LinkType) null); 
    compatibility.addAllowedGTUType(GTUType.WATERWAY_USER, LongitudinalDirectionality.DIR_BOTH); 
    WATERWAY = new LinkType("WATERWAY", null, compatibility); 
    // 
    compatibility = new GTUCompatibility<>((LinkType) null); 
    compatibility.addAllowedGTUType(GTUType.RAILWAY_USER, LongitudinalDirectionality.DIR_BOTH); 
    RAILWAY = new LinkType("RAILWAY", null, compatibility); 
    // 
    compatibility = new GTUCompatibility<>((LinkType) null); 
    compatibility.addAllowedGTUType(GTUType.ROAD_USER, LongitudinalDirectionality.DIR_PLUS); 
    compatibility.addAllowedGTUType(GTUType.WATERWAY_USER, LongitudinalDirectionality.DIR_PLUS); 
    compatibility.addAllowedGTUType(GTUType.RAILWAY_USER, LongitudinalDirectionality.DIR_PLUS); 
    CONNECTOR = new LinkType("CONNECTOR", null, compatibility); 
  -->

  <ots:LINKTYPE NAME="NONE" DEFAULT="true" />

  <ots:LINKTYPE NAME="ROAD" DEFAULT="true">
    <ots:COMPATIBILITY GTUTYPE="ROAD_USER" DIRECTION="BOTH" />
  </ots:LINKTYPE>

  <ots:LINKTYPE NAME="FREEWAY" PARENT="ROAD" DEFAULT="true">
    <ots:COMPATIBILITY GTUTYPE="ROAD_USER" DIRECTION="FORWARD" />
    <ots:COMPATIBILITY GTUTYPE="PEDESTRIAN" DIRECTION="NONE" />
    <ots:COMPATIBILITY GTUTYPE="BICYCLE" DIRECTION="NONE" />
  </ots:LINKTYPE>

  <ots:LINKTYPE NAME="WATERWAY" DEFAULT="true">
    <ots:COMPATIBILITY GTUTYPE="WATERWAY_USER" DIRECTION="BOTH" />
  </ots:LINKTYPE>

  <ots:LINKTYPE NAME="RAILWAY" DEFAULT="true">
    <ots:COMPATIBILITY GTUTYPE="RAILWAY_USER" DIRECTION="BOTH" />
  </ots:LINKTYPE>

  <ots:LINKTYPE NAME="CONNECTOR" DEFAULT="true">
    <ots:COMPATIBILITY GTUTYPE="ROAD_USER" DIRECTION="FORWARD" />
    <ots:COMPATIBILITY GTUTYPE="WATERWAY_USER" DIRECTION="FORWARD" />
    <ots:COMPATIBILITY GTUTYPE="RAILWAY_USER" DIRECTION="FORWARD" />
  </ots:LINKTYPE>
</ots:LINKTYPES>
