=== averbraeck/opentrafficsim/trunk/ots-xsd/src/main/resources/xsd/1.01.02/ots-network.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.opentrafficsim.org/ots"
  xmlns:ots="http://www.opentrafficsim.org/ots" xmlns="http://www.opentrafficsim.org/ots"
  xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  elementFormDefault="qualified">

  <!-- http://www.w3.org/2009/01/xml.xsd -->
  <xsd:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="../ref/xml.xsd" />
  <!-- http://www.w3.org/2001/xinclude.xsd -->
  <xsd:import namespace="http://www.w3.org/2001/XInclude" schemaLocation="../ref/xinclude.xsd" />

  <xsd:include schemaLocation="ots-definitions.xsd" />
  <xsd:include schemaLocation="ots-control.xsd" />

  <!-- https://opentrafficsim.org/docs/xsd/version/ots-definitions.xsd -->

  <!-- ================================================================================================== -->
  <!-- ================================================ NETWORK ========================================= -->
  <!-- ================================================================================================== -->

  <!-- The node name is the only key used as an ID, to allow for easy route and intermediate point definition -->

  <xsd:element name="NODE">
    <xsd:complexType>
      <xsd:attribute name="NAME" type="xsd:string" use="required" />
      <xsd:attribute name="COORDINATE" type="COORDINATETYPE" use="required" />
      <xsd:attribute name="DIRECTION" type="DIRECTIONTYPE" use="optional" />
      <xsd:attribute ref="xml:base" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="CONNECTOR">
    <xsd:complexType>
      <xsd:attribute name="NAME" type="xsd:string" use="required" />
      <xsd:attribute name="NODESTART" type="xsd:string" use="required" />
      <xsd:attribute name="NODEEND" type="xsd:string" use="required" />
      <xsd:attribute name="DEMANDWEIGHT" type="FRACTIONTYPE" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="LINK">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:choice>
          <xsd:element name="STRAIGHT" />
          <xsd:element name="BEZIER">
            <xsd:complexType>
              <xsd:attribute name="STARTDIRECTION" type="DIRECTIONTYPE" use="optional" />
              <xsd:attribute name="ENDDIRECTION" type="DIRECTIONTYPE" use="optional" />
              <xsd:attribute name="NUMSEGMENTS" type="xsd:integer" use="optional" default="64" />
              <xsd:attribute name="SHAPE" type="POSITIVEDOUBLE" use="optional" />
              <xsd:attribute name="WEIGHTED" type="xsd:boolean" use="optional" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="CLOTHOID">
            <xsd:complexType>
              <xsd:attribute name="STARTDIRECTION" type="DIRECTIONTYPE" use="optional" />
              <xsd:attribute name="STARTCURVATURE" type="PERLENGTHTYPE" use="required" />
              <xsd:attribute name="ENDDIRECTION" type="DIRECTIONTYPE" use="optional" />
              <xsd:attribute name="ENDCURVATURE" type="PERLENGTHTYPE" use="required" />
              <xsd:attribute name="LENGTH" type="LENGTHTYPE" use="optional" />
              <xsd:attribute name="ENDELEVATION" type="LENGTHTYPE" use="optional" />
              <xsd:attribute name="NUMSEGMENTS" type="xsd:integer" use="optional" default="64" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="ARC">
            <xsd:complexType>
              <xsd:attribute name="RADIUS" type="LENGTHTYPE" use="required" />
              <xsd:attribute name="DIRECTION" type="LEFTRIGHTTYPE" use="required" />
              <xsd:attribute name="NUMSEGMENTS" type="xsd:integer" use="optional" default="64" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="POLYLINE">
            <xsd:complexType>
              <xsd:attribute name="INTERMEDIATEPOINTS" type="COORDINATELISTTYPE" use="required" />
            </xsd:complexType>
          </xsd:element>
        </xsd:choice>

        <xsd:element ref="ROADLAYOUT" minOccurs="0" maxOccurs="1" />

        <xsd:element name="LANEOVERRIDE" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element ref="SPEEDLIMIT" minOccurs="0" maxOccurs="unbounded" />
            </xsd:sequence>
            <xsd:attribute name="LANE" type="xsd:string" use="required" />
            <xsd:attribute name="DIRECTION" type="DRIVINGDIRECTIONTYPE" use="optional" />
            <xsd:attribute name="OVERTAKING" type="OVERTAKINGTYPE" use="optional" />
          </xsd:complexType>
        </xsd:element>

        <!-- TODO EITHER GTU or GTUMIX should be present... -->
        <!-- TODO Maximum one of ROUTE, ROUTEMIX, SHORTESTROUTE, SHORTESTROUTEMIX should be present... -->
        <xsd:element name="GENERATOR" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:attribute name="LANE" type="xsd:string" use="required" />
            <xsd:attribute name="POSITION" type="LENGTHBEGINENDTYPE" use="required" />
            <xsd:attribute name="GTU" type="xsd:string" use="optional" />
            <xsd:attribute name="GTUMIX" type="xsd:string" use="optional" />
            <xsd:attribute name="IAT" type="TIMEDISTTYPE" use="required" />
            <xsd:attribute name="INITIALSPEED" type="SPEEDDISTTYPE" use="required" />
            <xsd:attribute name="MAXGTU" type="xsd:double" use="optional" />
            <xsd:attribute name="STARTTIME" type="TIMETYPE" use="optional" />
            <xsd:attribute name="ENDTIME" type="TIMETYPE" use="optional" />
            <xsd:attribute name="ROUTE" type="xsd:string" use="optional" />
            <xsd:attribute name="ROUTEMIX" type="xsd:string" use="optional" />
          </xsd:complexType>
        </xsd:element>

        <!-- TODO EITHER GTU or GTUMIX should be present... -->
        <!-- TODO Maximum one of ROUTE, ROUTEMIX, SHORTESTROUTE, SHORTESTROUTEMIX should be present... -->
        <xsd:element name="LISTGENERATOR" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:attribute name="URI" type="xsd:anyURI" use="required" />
            <xsd:attribute name="LANE" type="xsd:string" use="required" />
            <xsd:attribute name="POSITION" type="LENGTHBEGINENDTYPE" use="optional" />
            <xsd:attribute name="GTU" type="xsd:string" use="optional" />
            <xsd:attribute name="GTUMIX" type="xsd:string" use="optional" />
            <xsd:attribute name="INITIALSPEED" type="SPEEDDISTTYPE" use="required" />
            <xsd:attribute name="ROUTE" type="xsd:string" use="required" />
          </xsd:complexType>
        </xsd:element>

        <!-- TODO EITHER GTU or GTUGROUP should be present... -->
        <!-- TODO Maximum one of ROUTE, ROUTEMIX, SHORTESTROUTE, SHORTESTROUTEMIX should be present... -->
        <xsd:element name="FILL" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:attribute name="LANE" type="xsd:string" use="required" />
            <xsd:attribute name="GTU" type="xsd:string" use="optional" />
            <xsd:attribute name="GTUMIX" type="xsd:string" use="optional" />
            <xsd:attribute name="DISTANCE" type="LENGTHDISTTYPE" use="required" />
            <xsd:attribute name="INITIALSPEED" type="SPEEDDISTTYPE" use="required" />
            <xsd:attribute name="MAXGTU" type="xsd:double" use="optional" />
            <xsd:attribute name="ROUTE" type="xsd:string" use="required" />
          </xsd:complexType>
        </xsd:element>

        <xsd:element name="BLOCK" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:attribute name="LANE" type="xsd:string" use="required" />
            <xsd:attribute name="POSITION" type="LENGTHBEGINENDTYPE" use="required" />
          </xsd:complexType>
        </xsd:element>

        <xsd:element name="SENSOR" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:attribute name="NAME" type="xsd:string" use="optional" />
            <xsd:attribute name="LANE" type="xsd:string" use="required" />
            <xsd:attribute name="POSITION" type="LENGTHBEGINENDTYPE" use="required" />
            <xsd:attribute name="CLASS" type="CLASSNAMETYPE" use="required" />
            <xsd:attribute name="TRIGGER" type="GTUPOSITIONTYPE" use="required" />
          </xsd:complexType>
        </xsd:element>

        <xsd:element name="TRAFFICLIGHT" type="TRAFFICLIGHTTYPE" minOccurs="0" maxOccurs="unbounded" />

        <xsd:element name="SIGNALGROUP" type="SIGNALGROUPTYPE" minOccurs="0" maxOccurs="unbounded" />

        <xsd:element name="SINK" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:attribute name="LANE" type="xsd:string" use="required" />
            <xsd:attribute name="POSITION" type="LENGTHBEGINENDTYPE" use="required" />
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>

      <xsd:attribute name="NAME" type="xsd:string" use="required" />
      <xsd:attribute name="NODESTART" type="xsd:string" use="required" />
      <xsd:attribute name="NODEEND" type="xsd:string" use="required" />
      <xsd:attribute name="DEFINEDROADLAYOUT" type="xsd:string" use="optional" />
      <xsd:attribute name="OFFSETSTART" type="SIGNEDLENGTHTYPE" use="optional" default="0.0 m" />
      <xsd:attribute name="OFFSETEND" type="SIGNEDLENGTHTYPE" use="optional" default="0.0 m" />
      <xsd:attribute name="LANEKEEPING" type="LANEKEEPINGTYPE" use="optional" default="KEEPRIGHT" />
      <xsd:attribute name="PRIORITY" type="PRIORITYTYPE" use="optional" />
      <xsd:attribute ref="xml:base" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="ROUTE">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="NODE" minOccurs="2" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attribute name="NAME" type="xsd:string" use="required" />
      <xsd:attribute ref="xml:base" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="SHORTESTROUTE">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="FROM" type="xsd:string" minOccurs="1" maxOccurs="1" />
        <xsd:element name="TO" type="xsd:string" minOccurs="1" maxOccurs="1" />
        <xsd:element name="VIA" minOccurs="2" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attribute name="NAME" type="xsd:string" use="required" />
      <xsd:attribute name="DISTANCECOST" type="DISTANCECOSTTYPE" use="required" />
      <xsd:attribute name="TIMECOST" type="TIMECOSTTYPE" use="required" />
      <xsd:attribute ref="xml:base" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="ROUTEMIX">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="ROUTE" minOccurs="1" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:attribute name="NAME" type="xsd:string" use="required" />
            <xsd:attribute name="WEIGHT" type="xsd:double" use="required" />
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
      <xsd:attribute name="NAME" type="xsd:string" use="required" />
      <xsd:attribute ref="xml:base" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="SHORTESTROUTEMIX">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="SHORTESTROUTE" minOccurs="1" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:attribute name="NAME" type="xsd:string" use="required" />
            <xsd:attribute name="WEIGHT" type="xsd:double" use="required" />
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
      <xsd:attribute name="NAME" type="xsd:string" use="required" />
      <xsd:attribute ref="xml:base" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="SIGNALGROUP">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="TRAFFICLIGHT" type="SIGNALGROUPTRAFFICLIGHTTYPE" minOccurs="1"
          maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attribute name="ID" type="xsd:string" use="required" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="NETWORK">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="xi:include" minOccurs="0" maxOccurs="unbounded" />
        <xsd:element ref="NODE" minOccurs="0" maxOccurs="unbounded" />
        <xsd:element ref="CONNECTOR" minOccurs="0" maxOccurs="unbounded" />
        <xsd:element ref="LINK" minOccurs="0" maxOccurs="unbounded" />
        <xsd:element ref="ROUTE" minOccurs="0" maxOccurs="unbounded" />
        <xsd:element ref="ROUTEMIX" minOccurs="0" maxOccurs="unbounded" />
        <xsd:element ref="SHORTESTROUTE" minOccurs="0" maxOccurs="unbounded" />
        <xsd:element ref="SHORTESTROUTEMIX" minOccurs="0" maxOccurs="unbounded" />
        <xsd:element ref="SIGNALGROUP" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attribute ref="xml:base" />
    </xsd:complexType>
  </xsd:element>

</xsd:schema>

=== averbraeck/opentrafficsim/release/0.14.00/ots-parser-xml/src/test/resources/N201v8.xml
<?xml version="1.0" encoding="UTF-8" ?>
<NETWORK xmlns="http://www.opentrafficsim.org/ots" xmlns:ots="http://www.opentrafficsim.org/ots" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.opentrafficsim.org/ots http://www.opentrafficsim.org/docs/current/ots-network.xsd"
	xmlns:xi="http://www.w3.org/2001/XInclude">

	<DEFINITIONS>

		<GLOBAL />

		<GTUTYPE NAME="CAR" />

		<GTU NAME="CAR" GTUTYPE="CAR" LENGTH="CONST(4.5) m" WIDTH="CONST(2) m" MAXSPEED="CONST(80) km/h" />

		<ROADTYPE NAME="HIGHWAY" DEFAULTLANEWIDTH="3m" DEFAULTOVERTAKING="NONE" DEFAULTLANEKEEPING="KEEPLANE">
			<SPEEDLIMIT GTUTYPE="CAR" LEGALSPEEDLIMIT="100 km/h" />
		</ROADTYPE>
		<ROADTYPE NAME="OUTSIDECITY" DEFAULTLANEWIDTH="3m" DEFAULTOVERTAKING="NONE" DEFAULTLANEKEEPING="KEEPLANE">
			<SPEEDLIMIT GTUTYPE="CAR" LEGALSPEEDLIMIT="80 km/h" />
		</ROADTYPE>
		<ROADTYPE NAME="CITYSTREET" DEFAULTLANEWIDTH="3m" DEFAULTOVERTAKING="NONE" DEFAULTLANEKEEPING="KEEPLANE">
			<SPEEDLIMIT GTUTYPE="CAR" LEGALSPEEDLIMIT="50 km/h" />
		</ROADTYPE>

		<ROADLAYOUT NAME="RT1ln_ref-3" ROADTYPE="CITYSTREET">
			<LANE NAME="A1" OFFSET="-6m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
		</ROADLAYOUT>

		<ROADLAYOUT NAME="RT1ln_ref-2" ROADTYPE="CITYSTREET">
			<LANE NAME="A1" OFFSET="-9m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
		</ROADLAYOUT>

		<ROADLAYOUT NAME="RT1ln_ref-1" ROADTYPE="CITYSTREET">
			<LANE NAME="A1" OFFSET="-12m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
		</ROADLAYOUT>

		<ROADLAYOUT NAME="RT1ln_ref0" ROADTYPE="CITYSTREET">
			<LANE NAME="A1" OFFSET="-15m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
		</ROADLAYOUT>

		<ROADLAYOUT NAME="RT1ln_ref1" ROADTYPE="CITYSTREET">
			<LANE NAME="A1" OFFSET="-18m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
		</ROADLAYOUT>

		<ROADLAYOUT NAME="RT1ln_ref2" ROADTYPE="CITYSTREET">
			<LANE NAME="A1" OFFSET="-21m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
		</ROADLAYOUT>

		<ROADLAYOUT NAME="RT2ln_ref-3" ROADTYPE="OUTSIDECITY">
			<LANE NAME="A1" OFFSET="-6m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
			<STRIPE TYPE="DASHED" OFFSET="-4.5m" />
			<LANE NAME="A2" OFFSET="-3m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
		</ROADLAYOUT>

		<ROADLAYOUT NAME="RT2ln_ref-2" ROADTYPE="OUTSIDECITY">
			<LANE NAME="A1" OFFSET="-9m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
			<STRIPE TYPE="DASHED" OFFSET="-7.5m" />
			<LANE NAME="A2" OFFSET="-6m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
		</ROADLAYOUT>

		<ROADLAYOUT NAME="RT2ln_ref-1" ROADTYPE="OUTSIDECITY">
			<LANE NAME="A1" OFFSET="-12m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
			<STRIPE TYPE="DASHED" OFFSET="-10.5m" />
			<LANE NAME="A2" OFFSET="-9m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
		</ROADLAYOUT>

		<ROADLAYOUT NAME="RT2ln_ref0" ROADTYPE="OUTSIDECITY">
			<LANE NAME="A1" OFFSET="-15m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
			<STRIPE TYPE="DASHED" OFFSET="-13.5m" />
			<LANE NAME="A2" OFFSET="-12m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
		</ROADLAYOUT>

		<ROADLAYOUT NAME="RT2ln_ref1" ROADTYPE="OUTSIDECITY">
			<LANE NAME="A1" OFFSET="-18m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
			<STRIPE TYPE="DASHED" OFFSET="-16.5m" />
			<LANE NAME="A2" OFFSET="-15m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
		</ROADLAYOUT>

		<ROADLAYOUT NAME="RT2ln_ref2" ROADTYPE="OUTSIDECITY">
			<LANE NAME="A1" OFFSET="-21m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
			<STRIPE TYPE="DASHED" OFFSET="-19.5m" />
			<LANE NAME="A2" OFFSET="-18m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
		</ROADLAYOUT>

		<ROADLAYOUT NAME="RT2ln_ref4" ROADTYPE="OUTSIDECITY">
			<LANE NAME="A1" OFFSET="-27m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
			<STRIPE TYPE="DASHED" OFFSET="-25.5m" />
			<LANE NAME="A2" OFFSET="-24m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
		</ROADLAYOUT>

		<ROADLAYOUT NAME="RT3ln_ref-2" ROADTYPE="OUTSIDECITY">
			<LANE NAME="A1" OFFSET="-9m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
			<STRIPE TYPE="DASHED" OFFSET="-7.5m" />
			<LANE NAME="A2" OFFSET="-6m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
			<STRIPE TYPE="DASHED" OFFSET="-4.5m" />
			<LANE NAME="A3" OFFSET="-3m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
		</ROADLAYOUT>

		<ROADLAYOUT NAME="RT3ln_ref0" ROADTYPE="OUTSIDECITY">
			<LANE NAME="A1" OFFSET="-15m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
			<STRIPE TYPE="DASHED" OFFSET="-13.5m" />
			<LANE NAME="A2" OFFSET="-12m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
			<STRIPE TYPE="DASHED" OFFSET="-10.5m" />
			<LANE NAME="A3" OFFSET="-9m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
		</ROADLAYOUT>

		<ROADLAYOUT NAME="RT3ln_ref1" ROADTYPE="OUTSIDECITY">
			<LANE NAME="A1" OFFSET="-18m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
			<STRIPE TYPE="DASHED" OFFSET="-16.5m" />
			<LANE NAME="A2" OFFSET="-15m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
			<STRIPE TYPE="DASHED" OFFSET="-13.5m" />
			<LANE NAME="A3" OFFSET="-12m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
		</ROADLAYOUT>

		<ROADLAYOUT NAME="RT3ln_ref2" ROADTYPE="OUTSIDECITY">
			<LANE NAME="A1" OFFSET="-21m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
			<STRIPE TYPE="DASHED" OFFSET="-19.5m" />
			<LANE NAME="A2" OFFSET="-18m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
			<STRIPE TYPE="DASHED" OFFSET="-16.5m" />
			<LANE NAME="A3" OFFSET="-15m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
		</ROADLAYOUT>

		<ROADLAYOUT NAME="RT3ln_ref4" ROADTYPE="OUTSIDECITY">
			<LANE NAME="A1" OFFSET="-27m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
			<STRIPE TYPE="DASHED" OFFSET="-25.5m" />
			<LANE NAME="A2" OFFSET="-24m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
			<STRIPE TYPE="DASHED" OFFSET="-22.5m" />
			<LANE NAME="A3" OFFSET="-21m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
		</ROADLAYOUT>

		<ROADLAYOUT NAME="RT4ln_ref0" ROADTYPE="OUTSIDECITY">
			<LANE NAME="A1" OFFSET="-15m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
			<STRIPE TYPE="DASHED" OFFSET="-13.5m" />
			<LANE NAME="A2" OFFSET="-12m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
			<STRIPE TYPE="DASHED" OFFSET="-10.5m" />
			<LANE NAME="A3" OFFSET="-9m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
			<STRIPE TYPE="DASHED" OFFSET="-7.5m" />
			<LANE NAME="A4" OFFSET="-6m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
		</ROADLAYOUT>

		<ROADLAYOUT NAME="RT4ln_ref1" ROADTYPE="OUTSIDECITY">
			<LANE NAME="A1" OFFSET="-18m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
			<STRIPE TYPE="DASHED" OFFSET="-16.5m" />
			<LANE NAME="A2" OFFSET="-15m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
			<STRIPE TYPE="DASHED" OFFSET="-13.5m" />
			<LANE NAME="A3" OFFSET="-12m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
			<STRIPE TYPE="DASHED" OFFSET="-10.5m" />
			<LANE NAME="A4" OFFSET="-9m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
		</ROADLAYOUT>

		<ROADLAYOUT NAME="RT4ln_ref2" ROADTYPE="OUTSIDECITY">
			<LANE NAME="A1" OFFSET="-21m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
			<STRIPE TYPE="DASHED" OFFSET="-19.5m" />
			<LANE NAME="A2" OFFSET="-18m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
			<STRIPE TYPE="DASHED" OFFSET="-16.5m" />
			<LANE NAME="A3" OFFSET="-15m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
			<STRIPE TYPE="DASHED" OFFSET="-13.5m" />
			<LANE NAME="A4" OFFSET="-12m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
		</ROADLAYOUT>

		<ROADLAYOUT NAME="RT4ln_ref4" ROADTYPE="OUTSIDECITY">
			<LANE NAME="A1" OFFSET="-27m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
			<STRIPE TYPE="DASHED" OFFSET="-25.5m" />
			<LANE NAME="A2" OFFSET="-24m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
			<STRIPE TYPE="DASHED" OFFSET="-22.5m" />
			<LANE NAME="A3" OFFSET="-21m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
			<STRIPE TYPE="DASHED" OFFSET="-19.5m" />
			<LANE NAME="A4" OFFSET="-18m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
		</ROADLAYOUT>

		<ROADLAYOUT NAME="RT5ln_ref1" ROADTYPE="OUTSIDECITY">
			<LANE NAME="A1" OFFSET="-18m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
			<STRIPE TYPE="DASHED" OFFSET="-16.5m" />
			<LANE NAME="A2" OFFSET="-15m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
			<STRIPE TYPE="DASHED" OFFSET="-13.5m" />
			<LANE NAME="A3" OFFSET="-12m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
			<STRIPE TYPE="DASHED" OFFSET="-10.5m" />
			<LANE NAME="A4" OFFSET="-9m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
			<STRIPE TYPE="DASHED" OFFSET="-7.5m" />
			<LANE NAME="A5" OFFSET="-6m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
		</ROADLAYOUT>

		<ROADLAYOUT NAME="RT5ln_ref2" ROADTYPE="OUTSIDECITY">
			<LANE NAME="A1" OFFSET="-21m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
			<STRIPE TYPE="DASHED" OFFSET="-19.5m" />
			<LANE NAME="A2" OFFSET="-18m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
			<STRIPE TYPE="DASHED" OFFSET="-16.5m" />
			<LANE NAME="A3" OFFSET="-15m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
			<STRIPE TYPE="DASHED" OFFSET="-13.5m" />
			<LANE NAME="A4" OFFSET="-12m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
			<STRIPE TYPE="DASHED" OFFSET="-10.5m" />
			<LANE NAME="A5" OFFSET="-9m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
		</ROADLAYOUT>

		<ROADLAYOUT NAME="RT6ln_ref1" ROADTYPE="OUTSIDECITY">
			<LANE NAME="A1" OFFSET="-18m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
			<STRIPE TYPE="DASHED" OFFSET="-16.5m" />
			<LANE NAME="A2" OFFSET="-15m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
			<STRIPE TYPE="DASHED" OFFSET="-13.5m" />
			<LANE NAME="A3" OFFSET="-12m" WIDTH="3m" DIRECTION="FORWARD" COLOR="BLACK" />
			<STRIPE TYPE="DASHED" OFFSET="-10.5m" />
